####this script generates a dataframe with various splicing-related parameters for each immune cell type expression specificity subset
library(GenomicRanges)
library(BSgenome.Hsapiens.UCSC.hg38)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)

setwd("C:/data/TissueAbSplicing")

####Load & process exon reference file
#Read reference file generated by PrepareRefFileFromGTF.R
exRef <- read_delim("C:/dataprocessing/database/gencode/GENCODEv47_comprehensive_exons_v2.txt", delim = "\t", col_names = TRUE)

#keep top-ranked transcripts with more than 2 exons
exRef.txRank1 <- exRef %>%
  filter(geneType == "protein_coding") %>%
  filter(totalExNo > 2) %>%
  filter(txRank == 1)  %>%
  select(geneSym, geneID, txID, chr, exStart, exEnd, strand, exLen, exGC, downIntLen, downIntGC, MAXENT_3SS, MAXENT_5SS) %>%
  mutate(
    coord_3ss = ifelse(strand == "+", exStart, exEnd), #position of 3'ss (used for de-duplication later)
    coord_5ss = ifelse(strand == "+", exEnd, exStart), #position of 5'ss (used for de-duplication later)
    group = "allgenes", #dummy columns to match structure of downstream dataframes
    tissue = "allgenes",
    expressionType = "allgenes"
  )

####calculating GC content of regions upstream of genes & append to exon reference dataframe 
#distance to cover upstream
upstreamRegion <- 20000

#calculate coords of covered regions using the first exon of the transcripts
tx.upstr.GC <- exRef %>%
  filter(exNo == 1 & txRank == 1) %>%
  mutate(
    upstrStart = ifelse(strand == "+", exStart - upstreamRegion, exEnd + 1),
    upstrEnd = ifelse(strand == "+", exStart -1, exEnd + upstreamRegion)
  ) %>%
  mutate(coords.upstr = paste0(chr, ":", upstrStart, "-", upstrEnd, ":", strand))

#retrieve sequences
seqs.upstr <-
  as.character(
    BSgenome::getSeq(
      BSgenome.Hsapiens.UCSC.hg38,
      GRanges(tx.upstr.GC$coords.upstr)
      )
    )

#calculate GC% of sequences
tx.upstr.GC$upstrGC <- stringi::stri_count(seqs.upstr, regex = "G|C") / upstreamRegion
rm(seqs.upstr) #remove sequences from memory (no longer required)

#append to exon reference dataframe 
exRef.txRank1 <- exRef.txRank1 %>%
  left_join(., tx.upstr.GC %>% select(txID, upstrGC))

####Extending the exon reference dataframe by duplicating rows if they occur in a cell type specificity subset
#Using group, tissue and expression columns to keep track of which subsets they belong to
#Read HPA specificity matrix generated using HPAanalysis_groupingGenes.R
HPA.geneClasses <- read.table("./HPA_bloodSpecificityMatrix.txt", sep = "\t", header = TRUE)
#important that there are no underscores between celltype and expression specificity category in the column names

#if a gene appears in a subset, duplicate those rows in the exon reference dataframe and add it to a new list element
tempSubset <- vector("list", length = ncol(HPA.geneClasses))
tempSubset[[1]] <- exRef.txRank1
for(i in 2:ncol(HPA.geneClasses)){
  genes.sel <- HPA.geneClasses$geneID[HPA.geneClasses[,i] == TRUE]
  tempSubset[[i]] <- exRef.txRank1 %>%
    filter(geneID %in% genes.sel) %>%
    mutate(group = colnames(HPA.geneClasses)[i]) %>%
    mutate(tissue = gsub("_.*?$", "", colnames(HPA.geneClasses)[i])) %>%
    mutate(expressionType = gsub("^.*?_", "", colnames(HPA.geneClasses)[i]))
}
names(tempSubset) <- c("allgenes", colnames(HPA.geneClasses)[-1])

#rbind all list elements to generate an updated exon reference dataframe
allSubsets <- do.call(rbind, tempSubset) %>%
  mutate(tissue = factor(tissue, levels = unique(tissue)))

#collapse exon reference dataframe to gene-level averages (mean)
allSubsets.gene <- allSubsets %>%
  select(-exStart, -exEnd, -strand, -coord_3ss, -coord_5ss) %>% #not required for gene-level
  group_by(geneSym, geneID, chr, txID, group, tissue, expressionType) %>%
  summarise(
    exLen = mean(exLen, na.rm = TRUE),
    exGC = mean(exGC, na.rm = TRUE),
    downIntLen = mean(downIntLen, na.rm = TRUE), #actually represents mean intronic length as a whole now
    intGC = mean(downIntGC, na.rm = TRUE), #actually represents mean intronic GC as a whole now
    upstrGC = mean(upstrGC, na.rm = TRUE),
    MAXENT_3SS = mean(MAXENT_3SS, na.rm = TRUE),
    MAXENT_5SS = mean(MAXENT_5SS, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(tissue, expressionType, geneSym)

#some dataframes that can be removed to save on memory usage, if required
# rm(allSubsets)
#rm(exRef.txRank1)
#rm(exRef)

####Adding new classifications to reduce redundancies between highly similar subsets
#_typeE: cell-type enriched (1 cell type)
#_typeGE: group enriched (2-5 cell types)
#_group: these cell types have very little cell-type enriched genes (i.e. _typeE), so all enriched genes are aggregated
allSubsets.gene <- allSubsets.gene %>% filter(expressionType %in% c("allgenes", "enriched", "groupenriched", "enhanced")) %>%
  mutate(
    group2 =
      case_when(
        tissue %in% c("allgenes") ~ "allgenes",
        tissue %in% c("basophil") & expressionType %in% c("enriched") ~ "basophil_typeE",
        tissue %in% c("basophil") & expressionType %in% c("groupenriched") ~ "basophil_typeGE",
        tissue %in% c("eosinophil") & expressionType %in% c("enriched") ~ "eosinophil_typeE",
        tissue %in% c("eosinophil") & expressionType %in% c("groupenriched") ~ "eosinophil_typeGE",
        tissue %in% c("neutrophil") & expressionType %in% c("enriched") ~ "neutrophil_typeE",
        tissue %in% c("neutrophil") & expressionType %in% c("groupenriched") ~ "neutrophil_typeGE",
        tissue %in% c("nkcell") & expressionType %in% c("enriched","groupenriched") ~ "nkcell_type",
        tissue %in% c("plasmacytoiddc") & expressionType %in% c("enriched") ~ "pDC_typeE",
        tissue %in% c("plasmacytoiddc") & expressionType %in% c("groupenriched") ~ "pDC_typeGE",
        tissue %in% c("naivebcell", "memorybcell") & expressionType %in% c("enriched","groupenriched") ~ "bcell_group",
        tissue %in% c("naiveCD4tcell", "naiveCD8tcell", "memoryCD4tcell", "memoryCD8tcell", "treg") & expressionType %in% c("enriched","groupenriched") ~ "tcell_group",
        tissue %in% c("gammadeltatcell", "maittcell") & expressionType %in% c("enriched","groupenriched") ~ "tcell_group",
        tissue %in% c("classicalmonocyte", "intermediatemonocyte", "nonclassicalmonocyte", "myeloiddc") & expressionType %in% c("enriched","groupenriched") ~ "monocyte_mDC_group",
        TRUE ~ "drop" #for dropping all unwanted groups later ('enhanced' genes, in this case)
      )
  ) %>%
  ungroup() %>%
  filter(group2 != "drop") #do not drop unwanted groups if 'enhanced' genes are to be analysed

####filter genes by expression
#to focus on genes with higher expression
#read corresponding RNA-seq nTPM values from HPA (downloadable from the HPA website)
HPA.expr <- read.table("C:/data/PhD/thesis/data/RNAseq/databases/rna_blood_cell.tsv", sep = "\t", header = TRUE)
#rename cell type names to match our constructed dataframe
HPA.expr <- HPA.expr %>%
  mutate(
    tissue = case_when(
      Blood.cell == "basophil" ~ "basophil",
      Blood.cell == "classical monocyte" ~ "classicalmonocyte",
      Blood.cell == "eosinophil" ~ "eosinophil",
      Blood.cell == "gdT-cell" ~ "gammadeltatcell",
      Blood.cell == "intermediate monocyte" ~ "intermediatemonocyte",
      Blood.cell == "MAIT T-cell" ~ "maittcell",
      Blood.cell == "memory B-cell" ~ "memorybcell",
      Blood.cell == "memory CD4 T-cell" ~ "memoryCD4tcell",
      Blood.cell == "memory CD8 T-cell" ~ "memoryCD8tcell",
      Blood.cell == "myeloid DC" ~ "myeloiddc",
      Blood.cell == "naive B-cell" ~ "naivebcell",
      Blood.cell == "naive CD4 T-cell" ~ "naiveCD4tcell",
      Blood.cell == "naive CD8 T-cell" ~ "naiveCD8tcell",
      Blood.cell == "neutrophil" ~ "neutrophil",
      Blood.cell == "NK-cell" ~ "nkcell",
      Blood.cell == "non-classical monocyte" ~ "nonclassicalmonocyte",
      Blood.cell == "plasmacytoid DC" ~ "plasmacytoiddc",
      Blood.cell == "T-reg" ~ "treg",
      Blood.cell == "total PBMC" ~ "total PBMC",
      TRUE ~ "ERROR" #should not have any, if all cell types are covered
    )
  )

#join nTPM values to our gene-level reference dataframe and keep genes with >10 nTPM
allSubsets.gene <- allSubsets.gene %>%
  filter(expressionType %in% c("allgenes", "enriched", "groupenriched", "enhanced")) %>%
  left_join(., HPA.expr %>% select(geneID = Gene, tissue, nTPM), by = c("geneID", "tissue")) %>%
  filter(nTPM > 10 | group == "allgenes") 

#de-duplicate based on group2
allSubsets.gene <- allSubsets.gene %>% filter(!duplicated(paste0(geneSym, "_", group2)))

#calculate statistics as required
rstatix::wilcox_test(data = allSubsets.gene, formula = intGC~group2, ref.group = "allgenes", p.adjust.method = "BH")

#replot overlap matrices and gene counts per subset as necessary

# dataframe now ready as a base for parameter analysis and further annotation
