####This script assigns UniProt features onto exons (which can be further aggregated to annotate at gene-level)
library(GenomicRanges)
library(BSgenome.Hsapiens.UCSC.hg38)
library(dplyr)
library(tidyr)
library(readr)
library(pwalign)

setwd(paste0(dirname(rstudioapi::getActiveDocumentContext()$path)))

####
#Read reference file generated by PrepareRefFileFromGTF.R
exRef <- read_delim("C:/dataprocessing/database/gencode/GENCODEv47_comprehensive_exons_v2.txt", delim = "\t", col_names = TRUE) %>%
  filter(txType %in% ("protein_coding"))

#Read AA sequence file for AAs encoded by each coding exon
#Generated by A_getAAsequences_calcAAfreq.R
GENCODE_exonSeqs <- read.table("C:/dataprocessing/database/uniprot/GENCODEv47_comprehensive_exons_aaSeqs.txt", sep = "\t", header = TRUE, comment = "$") %>%
  mutate(coords = paste0(chr, ":", exonStart, "-", exonEnd, ":", strand))  %>%
  select(coords, exon.AAseq = AAseq)

#Read uniprot ID files (downloaded from UCSC table browser)
unip.IDs <- read.table(gzfile("C:/dataprocessing/database/uniprot/GENCODEv49_uniprotIDs_2.gz"), sep = "\t", header = TRUE, comment = "$", quote = "")
colnames(unip.IDs) <- c("txID", "geneID", "geneSym", "uniProtId")
unip.IDs$geneID <- gsub("\\..*?$", "", unip.IDs$geneID)
unip.IDs$txID <- gsub("\\..*?$", "", unip.IDs$txID)
#Read uniprot feature files, with exon boundary annotations (downloaded from UCSC table browser, UniProt track)
files.unipFunc <- c(
  "GENCODEv43_uniprot_domains.txt.gz",
  "GENCODEv43_uniprot_interest.txt.gz",
  "GENCODEv43_uniprot_other.txt.gz",
  "GENCODEv43_uniprot_SignalPeptide.txt.gz",
  "GENCODEv43_uniprot_transmembrane.txt.gz",
  "GENCODEv43_uniprot_structure.txt.gz"
)

unipFunc <- lapply(
  files.unipFunc,
  function(x){read.table(gzfile(x), sep = "\t", header = TRUE, comment = "$", quote = "")}
) %>%
  do.call(rbind, .)

#separate tx-level information into exon-level information
unipFunc.summ <- unipFunc %>%
  filter(!annotationType %in% c("non-standard amino acid", "non-terminal residue", "initiator methionine", "helix", "turn", "beta strand")) %>%
  mutate(geneID = unip.IDs$geneID[match(uniProtId, unip.IDs$uniProtId)]) %>%
  filter(!is.na(geneID)) %>%
  mutate(comments = ifelse(comments == "", longName, comments)) %>%
  select(geneID, uniProtId, start = chromStart, end = chromEnd, name = comments, position, annotationType, type, blockCount, blockSizes) %>%
  separate_rows(blockSizes, sep = ",", convert = TRUE) %>%
  group_by(geneID, uniProtId, position, start, end, name, annotationType, type, blockCount) %>%
  summarise(blockTotalLen = sum(blockSizes), .groups = "drop")

#find overlaps between feature-encoding CDS ranges (from UniProt/UCSC) and our main exon reference file
gr.domains <- GRanges(paste0(unipFunc.summ$geneID, ":", unipFunc.summ$start, "-", unipFunc.summ$end))
gr.exRef <- GRanges(paste0(exRef$geneID, ":", exRef$exStart, "-", exRef$exEnd))

index.intersect <- as.data.frame(findOverlaps(gr.exRef, gr.domains))

#calculate contribution of each exon CDS to forming a complete protein feature
df.intersect <- cbind(
  exRef %>% select(geneSym, geneID, txID, exNo, exType, chr, exStart, exEnd, strand, coords, affectsFrame, upIntGC, downIntGC) %>% dplyr::slice(index.intersect$queryHits),
  unipFunc.summ %>% select(-geneID) %>% dplyr::slice(index.intersect$subjectHits)
) %>%
  mutate(
    blockLen = pmin(exEnd, end) - pmax(exStart, start),
    blockPct = round(blockLen / blockTotalLen * 100, 2)
  ) %>%
  filter(exType %in% c("FCE", "ICE", "LCE", "SSE")) %>%
  arrange(geneSym, coords, -blockTotalLen) %>%
  mutate(AAseq = GENCODE_exonSeqs$exon.AAseq[match(coords, GENCODE_exonSeqs$coords)]) %>%
  filter(!is.na(AAseq))

####verify against UniProt reference AA sequences
#download human proteome AA sequences from UniProt website
uniprot.AAseqs <- read.table("C:/dataprocessing/database/uniprot/uniprotkb_proteome_UP000005640_AND_prot_2025_12_02.tsv",  sep = "\t", header = TRUE, quote = "", comment = "$")

#retrieve AA sequences for protein features, using UCSC-downloaded UniProt file information
unipSeq <- unipFunc %>%
  filter(!annotationType %in% c("non-standard amino acid", "non-terminal residue", "initiator methionine")) %>%
  select(uniProtId, name = comments, annotationType, position) %>%
  mutate(txID = unip.IDs$txID[match(uniProtId, unip.IDs$uniProtId)]) %>%
  filter(!is.na(txID)) %>%
  mutate(
    aaStart = as.numeric(stringr::str_extract(position, "(?<=acids ).*?(?=-)")),
    aaEnd = as.numeric(stringr::str_extract(position, "(?<=-).*?(?= on)"))
  ) %>%
  mutate(
    aaStart = ifelse(is.na(aaStart), stringr::str_extract(position, "(?<=acid ).*?(?= on)"), aaStart),
    aaEnd = ifelse(is.na(aaEnd), stringr::str_extract(position, "(?<=acid ).*?(?= on)"), aaEnd)
  ) %>%
  left_join(., uniprot.AAseqs %>% select(uniProtId = Entry, sequence = Sequence)) %>%
  mutate(
    sequence = substr(sequence, aaStart, aaEnd)
  ) %>%
  select(-txID) %>%
  distinct()

#Append AA sequence of full protein feature onto the exon-level protein features dataframe
df.intersect.match <- df.intersect %>%
  mutate(
    AAseq.fullDomain = unipSeq$sequence[match(paste0(uniProtId,":",position,":",annotationType), paste0(unipSeq$uniProtId,":",unipSeq$position,":",unipSeq$annotationType))]
  ) %>%
  filter(!is.na(AAseq.fullDomain))

sA <- AAStringSet(df.intersect.match$AAseq) #these are the AA sequences for exon CDS
sB <- AAStringSet(df.intersect.match$AAseq.fullDomain) #these are the AA sequences for the full protein feature that overlaps the exon CDS

#do pair-wise alignments between exon CDS and full protein features
n.rows <- length(sA)
interval <- 100000 #limit processing rate to reduce memory usage
n.intervals <-  ceiling(n.rows/interval)
list.tempAAalign <- vector("list", length = n.intervals)

for(i in 1:n.intervals){
  sA.subset <- sA[((i-1) * (interval) + 1):pmin(n.rows, (i * interval))]
  sB.subset <- sB[((i-1) * (interval) + 1):pmin(n.rows, (i * interval))]
  list.tempAAalign[[i]] <- as.character(pairwiseAlignment(sA.subset, sB.subset, type = "local")@pattern)
  list.tempAAalign[[i]] <- gsub("-", "", list.tempAAalign[[i]])
  print(i)
}
alignments.AB.char <- do.call(c, list.tempAAalign)

#rows to keep (exon CDS at least partially overlaps with full protein features)
index.match <- which(
  (nchar(alignments.AB.char)==(floor(df.intersect.match$blockLen/3)) & nchar(alignments.AB.char) > 0) |
    (nchar(alignments.AB.char)==(floor(df.intersect.match$blockLen/3)-1) & nchar(alignments.AB.char) > 0)
)

#remove exons with mismatching AA sequences
df.intersect.verified <- df.intersect.match %>%
  mutate(AAseq.partialDomain = alignments.AB.char) %>% #AA sequence derived from exon CDS, that forms part of a protein feature
  dplyr::slice(index.match) %>%
  #decide which features to keep here
  filter(annotationType %in% c("zinc finger region", "transmembrane region", "intramembrane region", "signal peptide", "domain", "compositionally biased region", "coiled-coil region", "DNA-binding region")) %>%
  arrange(txID, exNo, annotationType, name, blockPct) %>%
  filter(!duplicated(paste(txID, exNo, annotationType, name, sep = "_"))) %>%
  mutate(simpleName = gsub("( [0-9]{1,2}$)|( [0-9]{1,2};.*?$)", "", name, perl = TRUE)) %>%
  mutate(simpleName = case_when(
    annotationType %in% c("transmembrane region", "intramembrane region", "binding site", "active site", "signal peptide") ~ annotationType,
    simpleName == "" | is.na(simpleName) ~ annotationType,
    TRUE ~ simpleName
  )) %>%  #simplified name for downstream processing (many features are not clearly named or include feature numbers)
  filter(blockPct >= 10) %>% #at least 10% of the feature is encoded by this exon
  mutate(annotationType = gsub("-| ", "_", annotationType)) %>%
  group_by(txID, exNo, annotationType) %>%
  summarise(name = paste(simpleName, collapse = "; "), blockPct = paste(blockPct, collapse = "; "), .groups = "drop") %>%
  pivot_wider(names_from = annotationType, values_from = c(name, blockPct))

#export file
write.table(df.intersect.verified, "C:/dataprocessing/database/uniprot/GENCODEv47_exonUniprotFeats.txt", sep = "\t", row.names = FALSE, quote = FALSE)

######
