####This script filters and annotates rMATS outputs
library(BSgenome.Hsapiens.UCSC.hg38)
library(dplyr)
library(tidyr)
library(purrr)
library(stringi)
library(ggplot2)

setwd(paste0(dirname(rstudioapi::getActiveDocumentContext()$path)))

####Some functions to help filter and annotate AS events
splitC.NAzero <- function(x){
  res <- stri_split(x, fixed = ",", simplify = TRUE) %>%
    apply(., MARGIN = 2, FUN=as.numeric)
  res[is.na(res)] <- 0
  if(!is.matrix(res)){
    res <- matrix(res, nrow = 1)
  }
  return(res)
}


splitC.sel <- function(x, cols){
  res <- stri_split(x, fixed = ",", simplify = TRUE) %>%
    apply(., MARGIN = 2, FUN=as.numeric)
  res[is.na(res)] <- 0
  res <- res[,cols]
  return(res)
}

hash4 <- function(X){
  hash4_total <- 0
  for (i in 1:nchar(X[is.na(X) == FALSE])[1]){
    hash4_total <- hash4_total + as.numeric(substr(chartr("ACGT", "0123", X), i, i)) * 4^(nchar(X[is.na(X) == FALSE])[1]-i)
  }
  return(hash4_total)
} #for calcMAXENT

calcMAXENT_3SS <- function(X, me2x3){
  any.na <- any(is.na(X))
  if(any.na == TRUE){
    num_rows <- length(X)
    filled_rows <- which(!is.na(X))
    
    X <- X[!is.na(X)]
  }
  
  wt_3SS <- data.frame(Base = c("A", "C", "G", "T"),
                       bgd = c(0.27, 0.23, 0.23, 0.27),
                       N1 = c(0.9903, 0.0032, 0.0034, 0.0030),
                       N2 = c(0.0027, 0.0037, 0.9905, 0.0030)
  )
  
  scores <- log2(
    ((wt_3SS$N1[match(substr(X, 19, 19), wt_3SS$Base)] * wt_3SS$N2[match(substr(X, 20, 20), wt_3SS$Base)]) /
       (wt_3SS$bgd[match(substr(X, 19, 19), wt_3SS$Base)] * wt_3SS$bgd[match(substr(X, 20, 20), wt_3SS$Base)])) *
      ((me2x3[match(hash4(substr(X, 1, 7))+1, me2x3$Row), "acc1"] *
          me2x3[match(hash4(substr(X, 8, 14))+1, me2x3$Row), "acc2"] *
          me2x3[match(hash4(paste0(substr(X, 15, 18), substr(X, 21, 23)))+1, me2x3$Row), "acc3"] * 
          me2x3[match(hash4(substr(X, 5, 11))+1, me2x3$Row), "acc4"] *
          me2x3[match(hash4(substr(X, 12, 18))+1, me2x3$Row), "acc5"]) / 
         (me2x3[match(hash4(substr(X, 5, 7))+1, me2x3$Row), "acc6"] *
            me2x3[match(hash4(substr(X, 8, 11))+1, me2x3$Row), "acc7"] *
            me2x3[match(hash4(substr(X, 12, 14))+1, me2x3$Row), "acc8"] *
            me2x3[match(hash4(substr(X, 15, 18))+1, me2x3$Row), "acc9"]))
  )
  
  if(any.na == TRUE){
    X <- as.vector(matrix(NA, nrow = num_rows))
    X[filled_rows] <- scores
    return(X)
  } else {
    return(scores)
  }
} #for MAXENT 3'ss

calcMAXENT_5SS <- function(X, me2x5){
  any.na <- any(is.na(X))
  if(any.na == TRUE){
    num_rows <- length(X)
    filled_rows <- which(!is.na(X))
    
    X <- X[!is.na(X)]
  }
  
  wt_5SS <- data.frame(Base = c("A", "C", "G", "T"),
                       bgd = c(0.27, 0.23, 0.23, 0.27),
                       N1 = c(0.004, 0.0032, 0.9896, 0.0032),
                       N2 = c(0.0034, 0.0039, 0.0042, 0.9884)
  )
  
  scores <- log2(
    (wt_5SS$N1[match(substr(X, 4, 4), wt_5SS$Base)] * wt_5SS$N2[match(substr(X, 5, 5), wt_5SS$Base)]) /
      (wt_5SS$bgd[match(substr(X, 4, 4), wt_5SS$Base)] * wt_5SS$bgd[match(substr(X, 5, 5), wt_5SS$Base)]) *
      (me2x5$Value[match(paste0(substr(X, 1, 3), substr(X, 6, 9)), me2x5$Seq)])
  )
  
  if(any.na == TRUE){
    X <- as.vector(matrix(NA, nrow = num_rows))
    X[filled_rows] <- scores
    return(X)
  } else {
    return(scores)
  }
} #for MAXENT 5'ss

switchCoords_0_1 <- function(x){
  index.nonNA <- !is.na(x)
  gr <- GRanges(x[index.nonNA])
  start(gr) <- start(gr)+1
  newCoords <- as.character(gr)
  res <- rep(NA, length(x))
  res[index.nonNA] <- newCoords
  return(res)
} #switch 0-based to 1-based genomic coordinates (for sequence retrieval)


####Read required files
#For MAXENT calculations
me2x3 <- read.table("me2x3.csv", sep = ",", header = TRUE) 
me2x5 <- read.table("me2x5.csv", sep = ",", header = TRUE) 
#Exon reference file generated by PrepareRefFileFromGTF.R
exRef <- read.table("C:/dataprocessing/database/gencode/GENCODEv47_comprehensive_exons_v2.txt", sep = "\t", header = TRUE) %>%
  mutate(coords_1b = paste0(chr, ":", exStart+1, "-", exEnd, ":", strand)) #1-based coordinates
#AS effects on transcript function
exon_SERI_cons <- read.table("C:/dataprocessing/database/gencode/GENCODEv47_simulatedTxCons.txt", sep = "\t", header = TRUE, quote = "$")
exon_A3_cons <- read.table("C:/dataprocessing/database/gencode/GENCODEv47_simulatedTx_A3.txt", sep = "\t", header = TRUE, quote = "$")
exon_A5_cons <- read.table("C:/dataprocessing/database/gencode/GENCODEv47_simulatedTx_A5.txt", sep = "\t", header = TRUE, quote = "$")

####Pre-processing reference files
#Get all introns from exon ref file
exRef.int <- exRef %>%
  filter(!is.na(intronCoords.downst) & !duplicated(intronCoords.downst)) %>%
  mutate(coords.int_1b = switchCoords_0_1(intronCoords.downst)) %>%
  select(geneSym, coords.ex = coords_1b, coords.int = intronCoords.downst, coords.int_1b)

coords.int_1b <- unique(exRef.int$coords.int_1b)
coords.int_1b <- coords.int_1b[!is.na(coords.int_1b)]

#Remove redundant exons from exon ref after that
exRef <- exRef %>% filter(!duplicated(coords))

#Keep only cassette exons
exRef.SE <- exRef %>%
  filter(SE == TRUE)

#Some more re-naming
exon_SERI_cons <- exon_SERI_cons %>%
  mutate(
    exTxEff_L1 =
      case_when(
        exTxEff_L1 %in% c("aCT.ICE") & n_featTypes_downstr != 0 ~ "altCT.protFeat",
        exTxEff_L1 %in% c("aCT.LCE") & n.featTypes_ex != 0 ~ "altCT.protFeat",
        TRUE ~ exTxEff_L1
      )
  ) %>%
  mutate(
    dnIntTxEff_L1 =
      case_when(
        dnIntTxEff_L1 %in% c("insCDS_FS.ret", "intronicStop.ret") & n_featTypes_downstr != 0 ~ "altCT.protFeat",
        TRUE ~ dnIntTxEff_L1
      )
  )

exon_SERI_cons$coords_1b <- switchCoords_0_1(exon_SERI_cons$coords)
exon_SERI_cons$intronCoords.downst_1b <- switchCoords_0_1(exon_SERI_cons$intronCoords.downst)
exon_A3_cons <- exon_A3_cons %>%
  mutate(coords.extension = paste0(chr, ":", pmin(dist3SS, prox3SS)+1, "-", pmax(dist3SS, prox3SS), ":", strand))
exon_A5_cons <- exon_A5_cons %>%
  mutate(coords.extension = paste0(chr, ":", pmin(dist5SS, prox5SS)+1, "-", pmax(dist5SS, prox5SS), ":", strand))

####Filter and annotate a list of files rMATS results folders
datasets <- list.dirs("./rmatsres/")
datasets <- datasets[datasets != "./rmatsres/"]

datasets <- datasets[grepl("HL60", datasets)]

##Filter and annotate cassette exons
list.res.SE <- vector("list", length(datasets))

for(i in 1:length(datasets)){
  rmats.in <- read.table(paste0(datasets[i], "/SE.MATS.JC.txt"), sep = "\t", header = TRUE)
  n1 <- stri_count(rmats.in$IJC_SAMPLE_1[1], regex = ",")+1
  n2 <- stri_count(rmats.in$IJC_SAMPLE_2[1], regex = ",")+1
  
  rmats.proc <- rmats.in %>%
    filter(chr %in% paste0("chr", c(1:22,"X","Y"))) %>%
    mutate(
      IJC1 = splitC.NAzero(IJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC1 = splitC.NAzero(SJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      IJC2 = splitC.NAzero(IJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC2 = splitC.NAzero(SJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      TJC1 = IJC1 + SJC1,
      TJC2 = IJC2 + SJC2
    ) %>%
    mutate(
      upstJC1 = splitC.sel(upstream_to_target_count, 1:n1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      dnstJC1 = splitC.sel(target_to_downstream_count, 1:n1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      upstJC2 = splitC.sel(upstream_to_target_count, (n1+1):(n1+n2)) %>% rowMeans(na.rm = TRUE) %>% round(2),
      dnstJC2 = splitC.sel(target_to_downstream_count, (n1+1):(n1+n2)) %>% rowMeans(na.rm = TRUE) %>% round(2)
    ) %>%
    mutate(
      JC1.pct = pmin(upstJC1, dnstJC1) / (upstJC1 + dnstJC1) %>% round(2),
      JC2.pct = pmin(upstJC2, dnstJC2) / (upstJC2 + dnstJC2) %>% round(2)
    ) %>%
    filter(
      FDR <= 0.05 & abs(IncLevelDifference) >= 0.1 & TJC1 >= 20 & TJC2 >= 20 & pmax(JC1.pct, JC2.pct) >= 0.2
    ) %>%
    mutate(
      meanPSI1 = splitC.NAzero(IncLevel1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      meanPSI2 = splitC.NAzero(IncLevel2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      stat = ifelse(sign(IncLevelDifference) == -1, "UP", "DOWN")
    ) %>%
    select(
      GeneID, geneSymbol, chr, strand,
      exonStart_0base, exonEnd, upstreamES, upstreamEE, downstreamES, downstreamEE,
      stat, IncLevel1, IncLevel2, meanPSI1, meanPSI2, IncLevelDifference,
      IJC1, SJC1, TJC1, IJC2, SJC2, TJC2, JC1.pct, JC2.pct
    ) %>%
    mutate(
      coords = paste0(chr, ":", exonStart_0base+1, "-", exonEnd, ":", strand),
      fullcoords = paste0(coords,":",upstreamES, "-", upstreamEE, ":", downstreamES, "-", downstreamEE),
      coords.upstEx = paste0(chr, ":", ifelse(strand == "+", upstreamES, downstreamES), "-", ifelse(strand == "+", upstreamEE, downstreamEE), ":", strand),
      coords.dnstEx = paste0(chr, ":", ifelse(strand == "+", downstreamES, upstreamES), "-", ifelse(strand == "+", downstreamEE, upstreamEE), ":", strand),
      coords.upstInt = paste0(chr, ":", ifelse(strand == "+", upstreamEE+1, exonEnd+1), "-", ifelse(strand == "+", exonStart_0base, downstreamES), ":", strand),
      coords.dnstInt = paste0(chr, ":", ifelse(strand == "+", exonEnd+1, upstreamEE+1), "-", ifelse(strand == "+", downstreamES, exonStart_0base), ":", strand),
      coords.u5ss = paste0(chr, ":", ifelse(strand == "+", upstreamEE - (3-1), downstreamES - (6-1)), "-", ifelse(strand == "+", upstreamEE + (6), downstreamES + (3)), ":", strand),
      coords.3ss = paste0(chr, ":", ifelse(strand == "+", exonStart_0base - (20-1), exonEnd - (3-1)), "-", ifelse(strand == "+", exonStart_0base + (3), exonEnd + (20)), ":", strand),
      coords.5ss = paste0(chr, ":", ifelse(strand == "+", exonEnd - (3-1), exonStart_0base - (6-1)), "-", ifelse(strand == "+", exonEnd + (6), exonStart_0base + (3)), ":", strand),
      coords.d3ss = paste0(chr, ":", ifelse(strand == "+", downstreamES - (20-1), upstreamEE - (3-1)), "-", ifelse(strand == "+", downstreamES + (3), upstreamEE + (20)), ":", strand)
    ) %>%
    mutate(
      seq_u5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.u5ss))),
      seq_3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.3ss))),
      seq_5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.5ss))),
      seq_d3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.d3ss)))
    ) %>%
    mutate(
      ME_u5ss = calcMAXENT_5SS(seq_u5ss, me2x5),
      ME_3ss = calcMAXENT_3SS(seq_3ss, me2x3),
      ME_5ss = calcMAXENT_5SS(seq_5ss, me2x5),
      ME_d3ss = calcMAXENT_3SS(seq_d3ss, me2x3),
    ) %>%
    mutate(
      exLen = exonEnd - exonStart_0base,
      upIntLen = ifelse(strand == "+", exonStart_0base - upstreamEE, downstreamES - exonEnd),
      dnIntLen = ifelse(strand == "+", downstreamES - exonEnd, exonStart_0base - upstreamEE)
    ) %>%
    mutate(
      upIntGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.upstInt))) %>% stri_count(regex = "G|C")) / upIntLen) %>% round(4),
      exGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords))) %>% stri_count(regex = "G|C")) / exLen) %>% round(4),
      dnIntGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.dnstInt))) %>% stri_count(regex = "G|C")) / dnIntLen) %>% round(4)
    ) %>%
    mutate(
      annotatedEx = coords %in% exRef$coords_1b,
      exType = exRef$exType[match(coords, exRef$coords_1b)],
      txType = exRef$txType[match(coords, exRef$coords_1b)],
      annotatedSE = coords %in% exRef.SE$coords_1b
    ) %>%
    mutate(
      exTxEff = exon_SERI_cons$exTxEff_L1[match(coords, exon_SERI_cons$coords_1b)]
    ) %>%
    mutate(
      ASEtxEff =
        ifelse(sign(IncLevelDifference) == -1,
               case_when(
                 exTxEff %in% c("NMD.IncFS", "NMD.PTC") ~ "NMD.up",
                 exTxEff %in% c("NMD.SkipFS") ~ "NMD.down",
                 exTxEff %in% c("altProtFeat") ~ "protFeat.up",
                 exTxEff %in% c("FCE.loss") ~ "altFCE",
                 exTxEff %in% c("aCT.ICE", "aCT.LCE") ~ "altCT",
                 exTxEff %in% c("altCT.protFeat") ~ "altCT.protFeat",
                 exTxEff %in% c("nonCodingEx") ~ "notInCDS",
                 exTxEff %in% c("CDSinframe") ~ "CDSinframe"
                 is.na(exTxEff) ~ "noAnno",
                 TRUE ~ "noAnno"
               ),
               case_when(
                 exTxEff %in% c("NMD.IncFS", "NMD.PTC") ~ "NMD.down",
                 exTxEff %in% c("NMD.SkipFS") ~ "NMD.up",
                 exTxEff %in% c("altProtFeat") ~ "protFeat.down",
                 exTxEff %in% c("FCE.loss") ~ "altFCE",
                 exTxEff %in% c("aCT.ICE", "aCT.LCE") ~ "altCT",
                 exTxEff %in% c("altCT.protFeat") ~ "altCT.protFeat",
                 exTxEff %in% c("nonCodingEx") ~ "notInCDS",
                 exTxEff %in% c("CDSinframe") ~ "CDSinframe",
                 is.na(exTxEff) ~ "noAnno",
                 TRUE ~ "noAnno"
               )
        )
    ) %>%
    arrange(-abs(IncLevelDifference)) %>%#
    filter(!duplicated(coords)) %>%#
    arrange(IncLevelDifference)#
  
  list.res.SE[[i]] <- rmats.proc
  print(paste0("Finished dataset ", i, ":", datasets[i]))
}

names(list.res.SE) <- datasets

##Filter and annotate retained introns
list.res.RI <- vector("list", length(datasets))

for(i in 1:length(datasets)){
  rmats.in <- read.table(paste0(datasets[i], "/RI.MATS.JC.txt"), sep = "\t", header = TRUE)
  n1 <- stri_count(rmats.in$IJC_SAMPLE_1[1], regex = ",")+1
  n2 <- stri_count(rmats.in$IJC_SAMPLE_2[1], regex = ",")+1
  
  rmats.proc <- rmats.in %>%
    filter(chr %in% paste0("chr", c(1:22,"X","Y"))) %>%
    mutate(
      IJC1 = splitC.NAzero(IJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC1 = splitC.NAzero(SJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      IJC2 = splitC.NAzero(IJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC2 = splitC.NAzero(SJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      TJC1 = IJC1 + SJC1,
      TJC2 = IJC2 + SJC2
    ) %>%
    mutate(
      upstJC1 = splitC.sel(upstream_to_intron_count, 1:n1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      dnstJC1 = splitC.sel(intron_to_downstream_count, 1:n1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      upstJC2 = splitC.sel(upstream_to_intron_count, (n1+1):(n1+n2)) %>% rowMeans(na.rm = TRUE) %>% round(2),
      dnstJC2 = splitC.sel(intron_to_downstream_count, (n1+1):(n1+n2)) %>% rowMeans(na.rm = TRUE) %>% round(2)
    ) %>%
    mutate(
      JC1.pct = pmin(upstJC1, dnstJC1) / (upstJC1 + dnstJC1) %>% round(2),
      JC2.pct = pmin(upstJC2, dnstJC2) / (upstJC2 + dnstJC2) %>% round(2)
    ) %>%
    filter(
      TJC1 >= 20 & TJC2 >= 20 & pmax(JC1.pct, JC2.pct) >= 0.2
    ) 
  
    rmats.proc <- rmats.proc %>%
      mutate(
        meanPSI1 = splitC.NAzero(IncLevel1) %>% rowMeans(na.rm = TRUE) %>% round(2),
        meanPSI2 = splitC.NAzero(IncLevel2) %>% rowMeans(na.rm = TRUE) %>% round(2),
        stat = case_when(
          FDR <= 0.05 & IncLevelDifference >= 0.1 ~ "DOWN",
          FDR <= 0.05 & IncLevelDifference <= -0.1 ~ "UP",
          TRUE ~ "ns"
          )
      ) %>%
      filter(stat %in% c("UP","DOWN")) %>%
      select(
        GeneID, geneSymbol, chr, strand,
        riExonStart_0base, riExonEnd, upstreamES, upstreamEE, downstreamES, downstreamEE,
        stat, IncLevel1, IncLevel2, meanPSI1, meanPSI2, IncLevelDifference,
        IJC1, SJC1, TJC1, IJC2, SJC2, TJC2, JC1.pct, JC2.pct
      ) %>%
      mutate(
        coords.riEx = paste0(chr, ":", riExonStart_0base, "-", riExonEnd, ":", strand),
        coords.upstEx = paste0(chr, ":", ifelse(strand == "+", upstreamES+1, downstreamES+1), "-", ifelse(strand == "+", upstreamEE, downstreamEE), ":", strand),
        coords.dnstEx = paste0(chr, ":", ifelse(strand == "+", downstreamES+1, upstreamES+1), "-", ifelse(strand == "+", downstreamEE, upstreamEE), ":", strand),
        coords.intron = paste0(chr, ":", upstreamEE+1, "-", downstreamES, ":", strand),
        fullcoords = paste0(coords.riEx,":",upstreamES, "-", upstreamEE, ":", downstreamES, "-", downstreamEE),
        coords.u3ss = paste0(chr, ":", ifelse(strand == "+", riExonStart_0base - (20-1), riExonEnd - (3-1)), "-", ifelse(strand == "+", riExonStart_0base + (3), riExonEnd + (20)), ":", strand),
        coords.5ss = paste0(chr, ":", ifelse(strand == "+", upstreamEE - (3-1), downstreamES - (6-1)), "-", ifelse(strand == "+", upstreamEE + (6), downstreamES + (3)), ":", strand),
        coords.3ss = paste0(chr, ":", ifelse(strand == "+", downstreamES - (20-1), upstreamEE - (3-1)), "-", ifelse(strand == "+", downstreamES + (3), upstreamEE + (20)), ":", strand),
        coords.d5ss = paste0(chr, ":", ifelse(strand == "+", riExonEnd - (3-1), riExonStart_0base - (6-1)), "-", ifelse(strand == "+", riExonEnd + (6), riExonStart_0base + (3)), ":", strand)
      ) %>%
      mutate(
        seq_u3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.u3ss))),
        seq_5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.5ss))),
        seq_3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.3ss))),
        seq_d5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.d5ss)))
      ) %>%
      mutate(
        ME_u3ss = calcMAXENT_3SS(seq_u3ss, me2x3),
        ME_5ss = calcMAXENT_5SS(seq_5ss, me2x5),
        ME_3ss = calcMAXENT_3SS(seq_3ss, me2x3),
        ME_d5ss = calcMAXENT_5SS(seq_d5ss, me2x5),
      ) %>%
      mutate(
        exLen_upstream = ifelse(strand == "+", upstreamEE - upstreamES, downstreamEE - downstreamES),
        exLen_downstream = ifelse(strand == "+", downstreamEE - downstreamES, upstreamEE - upstreamES),
        intLen = downstreamES - upstreamEE
      ) %>%
      mutate(
        upExGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.upstEx))) %>% stri_count(regex = "G|C")) / exLen_upstream) %>% round(4),
        riGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.intron))) %>% stri_count(regex = "G|C")) / intLen) %>% round(4),
        dnExGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.dnstEx))) %>% stri_count(regex = "G|C")) / exLen_downstream) %>% round(4)
      ) %>%
      mutate(
        upstExType = exRef$exType[match(coords.upstEx, exRef$coords_1b)],
        dnstExType = exRef$exType[match(coords.dnstEx, exRef$coords_1b)]
      ) %>%
      mutate(
        intTxEff = exon_SERI_cons$dnIntTxEff_L1[match(coords.intron, exon_SERI_cons$intronCoords.downst_1b)]
      ) %>%
      mutate(
        ASEtxEff =
          ifelse(sign(IncLevelDifference) == -1,
                 case_when(
                   intTxEff %in% c("NMD.ret") ~ "NMD.up",
                   intTxEff %in% c("NMD.spl") ~ "NMD.down",
                   intTxEff %in% c("insCDS_FS.ret", "intronicStop.ret") ~ "FS_trunc.up",
                   intTxEff %in% c("altCT.protFeat") ~ "altCT.protFeat",
                   intTxEff %in% c("insCDS.ret") ~ "CDSins",
                   intTxEff %in% c("nonCodingGene") ~ "nonCodingGene",
                   intTxEff %in% c("notInCDS") ~ "notInCDS",
                   is.na(intTxEff) ~ "noAnno",
                   TRUE ~ "noAnno"
                 ),
                 case_when(
                   intTxEff %in% c("NMD.ret") ~ "NMD.down",
                   intTxEff %in% c("NMD.spl") ~ "NMD.up",
                   intTxEff %in% c("insCDS_FS.ret", "intronicStop.ret") ~ "FS_trunc.down",
                   intTxEff %in% c("altCT.protFeat") ~ "altCT.protFeat",
                   intTxEff %in% c("insCDS.ret") ~ "CDSdel",
                   intTxEff %in% c("nonCodingGene") ~ "nonCodingGene",
                   intTxEff %in% c("notInCDS") ~ "notInCDS",
                   is.na(intTxEff) ~ "noAnno",
                   TRUE ~ "noAnno"
                 )
          )
      ) %>%
      arrange(-abs(IncLevelDifference)) %>%#
      filter(!duplicated(coords.intron)) %>%#
      arrange(IncLevelDifference)#
  
  list.res.RI[[i]] <- rmats.proc
  print(paste0("Finished dataset ", i, ":", datasets[i]))
}

names(list.res.RI) <- datasets

##Filter and annotate alt. 5'ss
list.res.A5 <- vector("list", length(datasets))

for(i in 1:length(datasets)){
  rmats.in <- read.table(paste0(datasets[i], "/A5SS.MATS.JC.txt"), sep = "\t", header = TRUE)
  n1 <- stri_count(rmats.in$IJC_SAMPLE_1[1], regex = ",")+1
  n2 <- stri_count(rmats.in$IJC_SAMPLE_2[1], regex = ",")+1
  
  rmats.proc <- rmats.in %>%
    filter(chr %in% paste0("chr", c(1:22,"X","Y"))) %>%
    mutate(
      IJC1 = splitC.NAzero(IJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC1 = splitC.NAzero(SJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      IJC2 = splitC.NAzero(IJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC2 = splitC.NAzero(SJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      TJC1 = IJC1 + SJC1,
      TJC2 = IJC2 + SJC2
    ) %>%
    filter(
      FDR <= 0.05 & abs(IncLevelDifference) >= 0.1 & TJC1 >= 20 & TJC2 >= 20
    )

    rmats.proc <- rmats.proc %>%
      mutate(
        meanPSI1 = splitC.NAzero(IncLevel1) %>% rowMeans(na.rm = TRUE) %>% round(2),
        meanPSI2 = splitC.NAzero(IncLevel2) %>% rowMeans(na.rm = TRUE) %>% round(2),
        stat = ifelse(sign(IncLevelDifference) == -1, "LONG", "SHORT")
      ) %>%
      select(
        GeneID, geneSymbol, chr, strand,
        longExonStart_0base, longExonEnd, shortES, shortEE, flankingES, flankingEE,
        stat, IncLevel1, IncLevel2, meanPSI1, meanPSI2, IncLevelDifference,
        IJC1, SJC1, TJC1, IJC2, SJC2, TJC2
      ) %>%
      mutate(
        coords.shortEx = paste0(chr, ":", shortES+1,"-",shortEE,":", strand),
        coords.longEx = paste0(chr, ":", longExonStart_0base+1, "-", longExonEnd, ":", strand),
        coords.extension = paste0(chr, ":", ifelse(strand == "+", shortEE+1, longExonStart_0base+1), "-", ifelse(strand == "+", longExonEnd, shortES), ":", strand),
        coords.flankEx = paste0(chr, ":", flankingES+1, "-", flankingEE, ":", strand),
        coords.longExInt = paste0(chr, ":", ifelse(strand == "+", longExonEnd+1, flankingEE+1), "-", ifelse(strand == "+", flankingES, longExonStart_0base), ":", strand),
        coords.shortExInt = paste0(chr, ":", ifelse(strand == "+", shortEE+1, flankingEE+1), "-", ifelse(strand == "+", flankingES, shortES), ":", strand),
        fullcoords= paste0(chr, ":", shortES,"-",shortEE,":", longExonStart_0base, "-", longExonEnd, ":", strand,":",flankingES, "-", flankingEE),
        coords.3ss = paste0(chr, ":", ifelse(strand == "+", longExonStart_0base - (20-1), longExonEnd - (3-1)), "-", ifelse(strand == "+", longExonStart_0base + (3), longExonEnd + (20)), ":", strand),
        coords.prox5ss = paste0(chr, ":", ifelse(strand == "+", shortEE - (3-1), shortES - (6-1)), "-", ifelse(strand == "+", shortEE + (6), shortES + (3)), ":", strand),
        coords.dist5ss = paste0(chr, ":", ifelse(strand == "+", longExonEnd - (3-1), longExonStart_0base - (6-1)), "-", ifelse(strand == "+", longExonEnd + (6), longExonStart_0base + (3)), ":", strand),
        coords.d3ss = paste0(chr, ":", ifelse(strand == "+", flankingES - (20-1), flankingEE - (3-1)), "-", ifelse(strand == "+", flankingES + (3), flankingEE + (20)), ":", strand)
      )  %>%
      mutate(
        seq_3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.3ss))),
        seq_prox5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.prox5ss))),
        seq_dist5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.dist5ss))),
        seq_d3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.d3ss)))
      ) %>%
      mutate(
        ME_3ss = calcMAXENT_3SS(seq_3ss, me2x3),
        ME_prox5ss = calcMAXENT_5SS(seq_prox5ss, me2x5),
        ME_dist5ss = calcMAXENT_5SS(seq_dist5ss, me2x5),
        ME_d3ss = calcMAXENT_3SS(seq_d3ss, me2x3)
      ) %>%
      mutate(
        dnstIntLen_longEx = ifelse(strand == "+", flankingES - longExonEnd, longExonStart_0base - flankingEE),
        exLen_long = longExonEnd - longExonStart_0base,
        exLen_short = shortEE - shortES,
        exLen_extension = exLen_long - exLen_short,
        exLen_flanking = flankingEE - flankingES
      ) %>%
      mutate(
        shortExGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.shortEx))) %>% stri_count(regex = "G|C")) / exLen_short) %>% round(4),
        extensionGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.extension))) %>% stri_count(regex = "G|C")) / exLen_extension) %>% round(4),
        dnstIntGC_longEx = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.longExInt))) %>% stri_count(regex = "G|C")) / dnstIntLen_longEx) %>% round(4)
      ) %>%
      mutate(
        shortExType = exRef$exType[match(coords.shortEx, exRef$coords_1b)],
        longExType = exRef$exType[match(coords.longEx, exRef$coords_1b)],
        shortTxType = exRef$txType[match(coords.shortEx, exRef$coords_1b)],
        longTxType = exRef$txType[match(coords.longEx, exRef$coords_1b)],
      )
    
    ov <- as.data.frame(findOverlaps(GRanges(exRef.int$coords.int_1b), GRanges(rmats.proc$coords.extension), type = "within")) #%>%

    rmats.proc <- rmats.proc %>%
      filter(!1:nrow(.) %in% ov$subjectHits) %>%
      arrange(-abs(IncLevelDifference)) %>%#
      filter(!duplicated(coords.extension)) %>%#
      arrange(IncLevelDifference)#
    
    rmats.proc <- rmats.proc %>%
      mutate(
        A5TxEff = exon_A5_cons$A5TxEff_L1[match(coords.extension, exon_A5_cons$coords.extension)]
      ) %>%
      mutate(
        A5TxEff = case_when(
          (is.na(A5TxEff) | A5TxEff == "noAnno") & shortExType %in% c("3UTR","5UTR","LCE","NCE") & longExType %in% c("3UTR","5UTR","LCE","NCE") ~ "notInCDS",
          TRUE ~ A5TxEff
        )
      ) %>%
      mutate(
        ASEtxEff =
          ifelse(sign(IncLevelDifference) == -1,
                 case_when(
                   A5TxEff %in% c("fsNMD_dist", "PTC_dist") ~ "NMD.up",
                   A5TxEff %in% c("PTC_prox", "fsNMD_prox") ~ "NMD.down",
                   A5TxEff %in% c("indelCDS") ~ "indelCDS",
                   A5TxEff %in% c("fsCDS") ~ "fsCDS",
                   A5TxEff %in% c("notInCDS") ~ "notInCDS",
                   is.na(A5TxEff) ~ "noAnno",
                   TRUE ~ "noAnno"
                 ),
                 case_when(
                   A5TxEff %in% c("fsNMD_dist", "PTC_dist") ~ "NMD.down",
                   A5TxEff %in% c("PTC_prox", "fsNMD_prox") ~ "NMD.up",
                   A5TxEff %in% c("indelCDS") ~ "indelCDS",
                   A5TxEff %in% c("fsCDS") ~ "fsCDS",
                   A5TxEff %in% c("notInCDS") ~ "notInCDS",
                   is.na(A5TxEff) ~ "noAnno",
                   TRUE ~ "noAnno"
                 )
          )
      )

  list.res.A5[[i]] <- rmats.proc
  print(paste0("Finished dataset ", i, ":", datasets[i]))
}

names(list.res.A5) <- datasets

##Filter and annotate alt. 3'ss
list.res.A3 <- vector("list", length(datasets))

for(i in 1:length(datasets)){
  rmats.in <- read.table(paste0(datasets[i], "/A3SS.MATS.JC.txt"), sep = "\t", header = TRUE)
  n1 <- stri_count(rmats.in$IJC_SAMPLE_1[1], regex = ",")+1
  n2 <- stri_count(rmats.in$IJC_SAMPLE_2[1], regex = ",")+1
  
  rmats.proc <- rmats.in %>%
    filter(chr %in% paste0("chr", c(1:22,"X","Y"))) %>%
    mutate(
      IJC1 = splitC.NAzero(IJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC1 = splitC.NAzero(SJC_SAMPLE_1) %>% rowMeans(na.rm = TRUE) %>% round(2),
      IJC2 = splitC.NAzero(IJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      SJC2 = splitC.NAzero(SJC_SAMPLE_2) %>% rowMeans(na.rm = TRUE) %>% round(2),
      TJC1 = IJC1 + SJC1,
      TJC2 = IJC2 + SJC2
    ) %>%
    filter(
      FDR <= 0.05 & abs(IncLevelDifference) >= 0.1 & TJC1 >= 20 & TJC2 >= 20
    ) 
  
    rmats.proc <- rmats.proc %>%
      mutate(
        meanPSI1 = splitC.NAzero(IncLevel1) %>% rowMeans(na.rm = TRUE) %>% round(2),
        meanPSI2 = splitC.NAzero(IncLevel2) %>% rowMeans(na.rm = TRUE) %>% round(2),
        stat = ifelse(sign(IncLevelDifference) == -1, "LONG", "SHORT")
      ) %>%
      select(
        GeneID, geneSymbol, chr, strand,
        longExonStart_0base, longExonEnd, shortES, shortEE, flankingES, flankingEE,
        stat, IncLevel1, IncLevel2, meanPSI1, meanPSI2, IncLevelDifference,
        IJC1, SJC1, TJC1, IJC2, SJC2, TJC2
      ) %>%
      mutate(
        coords.shortEx = paste0(chr, ":", shortES+1,"-",shortEE,":", strand),
        coords.longEx = paste0(chr, ":", longExonStart_0base+1, "-", longExonEnd, ":", strand),
        coords.extension = paste0(chr, ":", ifelse(strand == "+", longExonStart_0base+1, shortEE+1), "-", ifelse(strand == "+", shortES, longExonEnd), ":", strand),
        coords.flankEx = paste0(chr, ":", flankingES+1, "-", flankingEE, ":", strand),
        coords.longExInt = paste0(chr, ":", ifelse(strand == "+", flankingEE+1, longExonEnd+1), "-", ifelse(strand == "+", longExonStart_0base, flankingES), ":", strand),
        coords.shortExInt = paste0(chr, ":", ifelse(strand == "+", flankingEE+1, shortEE+1), "-", ifelse(strand == "+", shortES, flankingES), ":", strand),
        fullcoords= paste0(chr, ":", shortES,"-",shortEE,":", longExonStart_0base, "-", longExonEnd, ":", strand,":",flankingES, "-", flankingEE),
        coords.u5ss = paste0(chr, ":", ifelse(strand == "+", flankingEE - (3-1), flankingES - (6-1)), "-", ifelse(strand == "+", flankingEE + (6), flankingES + (3)), ":", strand),
        coords.prox3ss = paste0(chr, ":", ifelse(strand == "+", shortES - (20-1), shortEE - (3-1)), "-", ifelse(strand == "+", shortES + (3), shortEE + (20)), ":", strand),
        coords.dist3ss = paste0(chr, ":", ifelse(strand == "+", longExonStart_0base - (20-1), longExonEnd - (3-1)), "-", ifelse(strand == "+", longExonStart_0base + (3), longExonEnd + (20)), ":", strand),
        coords.5ss = paste0(chr, ":", ifelse(strand == "+", longExonEnd - (3-1), longExonStart_0base - (6-1)), "-", ifelse(strand == "+", longExonEnd + (6), longExonStart_0base + (3)), ":", strand)
      )  %>%
      mutate(
        seq_u5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.u5ss))),
        seq_prox3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.prox3ss))),
        seq_dist3ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.dist3ss))),
        seq_5ss = as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.5ss)))
      ) %>%
      mutate(
        ME_u5ss = calcMAXENT_5SS(seq_u5ss, me2x5),
        ME_prox3ss = calcMAXENT_3SS(seq_prox3ss, me2x3),
        ME_dist3ss = calcMAXENT_3SS(seq_dist3ss, me2x3),
        ME_5ss = calcMAXENT_5SS(seq_5ss, me2x5)
      ) %>%
      mutate(
        upstIntLen_longEx = ifelse(strand == "+", longExonStart_0base - flankingEE, flankingES - longExonEnd),
        exLen_long = longExonEnd - longExonStart_0base,
        exLen_short = shortEE - shortES,
        exLen_extension = exLen_long - exLen_short,
        exLen_flanking = flankingEE - flankingES
      ) %>%
      mutate(
        shortExGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.shortEx))) %>% stri_count(regex = "G|C")) / exLen_short) %>% round(4),
        extensionGC = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.extension))) %>% stri_count(regex = "G|C")) / exLen_extension) %>% round(4),
        upstIntGC_longEx = ((as.character(getSeq(BSgenome.Hsapiens.UCSC.hg38, GRanges(coords.longExInt))) %>% stri_count(regex = "G|C")) / upstIntLen_longEx) %>% round(4)
      ) %>%
      mutate(
        shortExType = exRef$exType[match(coords.shortEx, exRef$coords_1b)],
        longExType = exRef$exType[match(coords.longEx, exRef$coords_1b)],
        shortTxType = exRef$txType[match(coords.shortEx, exRef$coords_1b)],
        longTxType = exRef$txType[match(coords.longEx, exRef$coords_1b)]
      )
    
    ov <- as.data.frame(findOverlaps(GRanges(exRef.int$coords.int_1b), GRanges(rmats.proc$coords.extension), type = "within")) #%>%

    rmats.proc <- rmats.proc %>%
      filter(!1:nrow(.) %in% ov$subjectHits) %>%
      arrange(-abs(IncLevelDifference)) %>%#
      filter(!duplicated(coords.extension)) %>%#
      arrange(IncLevelDifference)#
    
    rmats.proc <- rmats.proc %>%
      mutate(
        A3TxEff = exon_A3_cons$A3TxEff_L1[match(coords.extension, exon_A3_cons$coords.extension)]
      ) %>%
      mutate(
        A3TxEff = case_when(
          (is.na(A3TxEff) | A3TxEff == "noAnno") & shortExType %in% c("3UTR","5UTR","FCE","NCE") & longExType %in% c("3UTR","5UTR","FCE","NCE") ~ "notInCDS",
          TRUE ~ A3TxEff
        )
      ) %>%
      mutate(
        ASEtxEff =
          ifelse(sign(IncLevelDifference) == -1,
                 case_when(
                   A3TxEff %in% c("fsNMD_dist", "PTC_dist") ~ "NMD.up",
                   A3TxEff %in% c("PTC_prox", "fsNMD_prox") ~ "NMD.down",
                   A3TxEff %in% c("indelCDS") ~ "indelCDS",
                   A3TxEff %in% c("fsCDS") ~ "fsCDS",
                   A3TxEff %in% c("notInCDS") ~ "notInCDS",
                   is.na(A3TxEff) ~ "noAnno",
                   TRUE ~ "noAnno"
                 ),
                 case_when(
                   A3TxEff %in% c("fsNMD_dist", "PTC_dist") ~ "NMD.down",
                   A3TxEff %in% c("PTC_prox", "fsNMD_prox") ~ "NMD.up",
                   A3TxEff %in% c("indelCDS") ~ "indelCDS",
                   A3TxEff %in% c("fsCDS") ~ "fsCDS",
                   A3TxEff %in% c("notInCDS") ~ "notInCDS",
                   is.na(A3TxEff) ~ "noAnno",
                   TRUE ~ "noAnno"
                 )
          )
      )
  
  list.res.A3[[i]] <- rmats.proc
  print(paste0("Finished dataset ", i, ":", datasets[i]))
}

names(list.res.A3) <- datasets

####Results are now ready for analysing splicing parameters
