####this script is used to predict the functional effects of alternative splicing events by simulating them on GENCODE transcripts
library(GenomicRanges)
library(BSgenome.Hsapiens.UCSC.hg38)
library(Biostrings)
library(dplyr)
library(tidyr)
library(stringr)

setwd("C:/DataProcessing/Database/Gencode")

####Load & process exon reference file
#Read reference file generated by PrepareRefFileFromGTF.R
exons <- read.table("./GENCODEv47_comprehensive_exons_concise_v2.txt", sep = "\t", header = TRUE)
#set reference genome to human hg38
genome <- BSgenome.Hsapiens.UCSC.hg38

####calculate CDS and reading frame lengths encoded by each exon, as well as the last EJC position
##As a clarification on terminology used
#CDS: between translation start and stop
#RF/reading frame: from translation start till the end of the transcript (i.e. includes 3'UTR)
exons <- exons %>%
  mutate(
    exCDSLen = case_when(
      exType %in% c("NCE", "5UTR", "3UTR") ~ as.integer(0),
      exType %in% c("SET", "SSE") ~ as.integer(cdsEnd - cdsStart),
      exType %in% c("FCE") ~ as.integer(ifelse(strand == "+", exEnd - cdsStart, cdsEnd - exStart)),
      exType %in% c("LCE") ~ as.integer(ifelse(strand == "+", cdsEnd - exStart, exEnd - cdsStart)),
      exType %in% c("ICE") ~ as.integer(exEnd - exStart),
      TRUE ~ NA_integer_
    ) # CDS length encoded by each exon
  ) %>%
  group_by(txID) %>%
  mutate(
    cCDSLen = cumsum(exCDSLen),  # running sum of exon CDS lengths
    totalCDSLen = max(cCDSLen) # total transcript-level sum of exon CDS lengths
  ) %>%
  ungroup() %>%
  mutate(
    exRFLen = case_when( #RFLen: reading frame length (to contrast from CDS length, which stops at the stop codon)
      exType %in% c("NCE", "5UTR") ~ as.integer(0),
      exType %in% c("SET", "SSE") ~ as.integer(cdsEnd - cdsStart),
      exType %in% c("FCE") ~ as.integer(ifelse(strand == "+", exEnd - cdsStart, cdsEnd - exStart)),
      exType %in% c("ICE","LCE","3UTR") ~ as.integer(exEnd - exStart),
      TRUE ~ NA_integer_
    ) # reading frame length encoded by each exon
  ) %>%
  group_by(txID) %>%
  mutate(
    cRFLen = cumsum(exRFLen),  # running sum of exon RF lengths
    totalRFLen = max(cRFLen), # total transcript-level sum of exon RF lengths
    lastEJC_RFLen = ifelse(totalExNo != 1 & exType != "NCE", nth(cRFLen, n = -2,), NA)
  ) %>%  # cumulative RF length of second last exon (i.e. last EJC position relative to transcript coordinates)
  mutate(
    exonCDSstart = pmax(as.numeric(cdsStart), as.numeric(exStart))+1, #+1 to shift from 0-based to 1-based coordinates
    exonCDSend = pmin(as.numeric(cdsEnd), as.numeric(exEnd))
  ) %>% #for first and last coding exons, we need to take into account the fact that only part of the exon is protein coding
  mutate(
    coords.CDS = paste0(chr, ":", exonCDSstart, "-", exonCDSend, ":", strand),
    coords.RF = case_when(
      exType %in% c("FCE") ~ paste0(chr, ":", exonCDSstart, "-", exonCDSend, ":", strand),
      exType %in% c("ICE","LCE","3UTR") ~ paste0(chr, ":", exStart+1, "-", exEnd, ":", strand),
      TRUE ~ NA
  )
  ) %>% # generate genomic coordinates for each exon (CDS and RF)
  mutate(txID_coords = paste0(txID, "_", coords)) #as an identifier for tracing back results

####Pull RF coordinates of protein coding exons + 3'UTR (latter is improtant for predicting NMD)
coords.PCGonly <- exons %>% filter(geneType == "protein_coding") %>% filter(exType %in% c("FCE","ICE","LCE","3UTR")) %>% pull(coords.RF) %>% unique()
gr.PCGonly <- GRanges(coords.PCGonly)
#retrieve sequences of RF regions
seq.PCGonly <- as.character(getSeq(genome, gr.PCGonly))
#name the vector for tracing back
names(seq.PCGonly) <- coords.PCGonly
#append RF sequences back to main exon dataframe
exons <- exons %>%
  ungroup() %>%
  mutate(seq.RF = seq.PCGonly[match(coords.RF, names(seq.PCGonly))])
#remove sequences from memory if necessary
#rm(seq.PCGonly)

#assemble transcript RF sequences by concatenating exon RF sequences
seq.tx <- exons %>%
  group_by(txID) %>%
  filter(!is.na(seq.RF)) %>% #drop exons with no RF sequence (i.e. non-coding exons, 5'UTRs...)
  summarise(seq.RF = paste(seq.RF, collapse = ""), .groups = "drop") %>%
  mutate(n = seq.int(1, nrow(.), 1)) #this is an index for matching purposes later
#we don't want (and don't need) to directly append long sequences back to the exon-level dataframe

#append the seq.tx index back to the main exon-level dataframe (for matching purposes later)
exons$seq.ind <- seq.tx$n[match(exons$txID, seq.tx$txID)]

####Exon functional annotation
##simulating exon skipping
#this function drops out a sequence between dropPos.start & dropPos.end
# seq.tx.ind is the seq.tx index that we defined earlier
# we use seq.tx for the first argument (seq) of the function
genNewTx <- function(seq, dropPos.start, dropPos.end, seq.tx.ind){
  res <- paste0(substr(seq[seq.tx.ind], 1, dropPos.start), substr(seq[seq.tx.ind], dropPos.end+1, nchar(seq[seq.tx.ind])))
  return(res)
}

#simulate exon skipping of internal and last coding exons using genNewTx function
n.rows <- nrow(exons)
interval <- 200000 #number to process at a time; adjust if necessary
n.intervals <-  ceiling(n.rows/interval)
list.temp <- vector("list", length = n.intervals)

for(i in 1:n.intervals){
list.temp[[i]] <- exons %>%
  slice(((i-1) * (interval) + 1):pmin(n.rows, (i * interval))) %>%
  filter(geneType == "protein_coding") %>%
  filter(exType %in% c("ICE","LCE")) %>%
  filter(!grepl("cds_start_NF|cds_end_NF", tags)) %>% #remove transcripts with no defined CDS start or stop
  mutate(
    seq.RFnew =
      genNewTx(
        seq.tx$seq.RF,
        cRFLen - exRFLen, #i.e. RF position at start of exon
        cRFLen, #i.e. RF position at end of exon
        seq.ind)
    ) %>% #RF positions used to drop out exon sequences
  mutate(
    stop.CDSnew =
      translate(DNAStringSet(seq.RFnew)) %>% #translate new RF sequence
         gsub("(?<=\\*).*?$", "", ., perl = TRUE) %>% #remove all sequences after first stop codon
      nchar(.)*3 #multiply AA length by 3 to get nt position of stop codon
    ) %>%
  mutate(
    lastEJC_RFLenNew = lastEJC_RFLen - exCDSLen #this is the new last EJC position
  ) %>%
  mutate(
    distLEJC.CDSori = (lastEJC_RFLen - totalCDSLen), 
    distLEJC.CDSnew = (lastEJC_RFLenNew - stop.CDSnew)
  ) %>% #distances to last EJC in original and new transcript (positive values mean upstream of last EJC)
  mutate(
    exFrame = (exLen %% 3) #check exon frame
  ) %>%
  select(-seq.RFnew)
print(i)
}

##NMD status of original and simulated transcripts
exons_CE <- do.call(rbind, list.temp) %>%
  mutate(
    NMD.stat.ori = case_when(
      distLEJC.CDSori >= 50 & (exLen >= 400 | totalCDSLen <= 100) ~ "NMD.lo", #possible chance of NMD mitigation?
      distLEJC.CDSori >= 50 ~ "NMD.hi", #higher chance of NMD
      TRUE ~ "Coding" # likely no NMD
    ),
    NMD.stat.new = case_when(
      distLEJC.CDSnew >= 50 & (exLen >= 400 | stop.CDSnew <= 100) ~ "NMD.lo",
      distLEJC.CDSnew >= 50 ~ "NMD.hi",
      TRUE ~ "Coding"
    ) #we treat NMD.lo and NMD.hi as NMD substrates for this analysis, but one could keep both categories seperate if desired
  ) %>%
  mutate(
    NMD.stat.pair = paste0(NMD.stat.ori, ":::", NMD.stat.new) #NMD status of original vs simulated
  ) %>%
  mutate(txID_coords = paste0(txID, "_", coords))

#(NMD tx becomes coding tx after skipping the exon)
#exons that induce NMD upon inclusion due to carried PTC
exons.PTC <- exons_CE %>%
  filter(NMD.stat.pair %in% c("NMD.hi:::Coding", "NMD.lo:::Coding")) %>%
  filter(exType == "LCE") %>%
  filter(!coords %in% (exons_CE %>% filter(NMD.stat.ori == "Coding") %>% pull(coords)))

exons.sjPTC <- exons_CE %>%
  filter(NMD.stat.pair %in% c("NMD.hi:::Coding", "NMD.lo:::Coding")) %>%
  filter(exType == "ICE" & exFrame == 0) %>%
  filter(!coords %in% (exons_CE %>% filter(NMD.stat.ori == "Coding") %>% pull(coords)))

#exons that induce NMD upon inclusion due to downstream frameshifting
exons.ifsNMD <- exons_CE %>%
  filter(NMD.stat.pair %in% c("NMD.hi:::Coding", "NMD.lo:::Coding")) %>%
  filter(exType == "ICE" & exFrame != 0) %>%
  filter(!coords %in% (exons_CE %>% filter(NMD.stat.ori == "Coding") %>% pull(coords)))

#(coding tx becomes NMD tx after skipping the exon)
#exons that induce NMD upon skipping due to downstream frameshifting
exons.sfsNMD <- exons_CE %>%
  filter(NMD.stat.pair %in% c("Coding:::NMD.hi", "Coding:::NMD.lo")) %>%
  filter(exType == "ICE" & exFrame != 0)

#(coding tx is still a coding tx after skipping the exon)
#exons that induce downstream frameshifting but does not induce NMD
exons.ICE.altCT <- exons_CE %>%
  filter(NMD.stat.pair == "Coding:::Coding") %>%
  filter(exType == "ICE" & exFrame != 0)

#exons that allows an alternative last coding exon when skipped
exons.LCE.altCT <- exons_CE %>%
  filter(NMD.stat.pair == "Coding:::Coding") %>%
  filter(exType == "LCE" & (totalExNo != exNo))

#exons that allows an alternative last coding exon when skipped
exons.ICE.CDSlost <- exons_CE %>%
  filter(NMD.stat.pair == "Coding:::Coding") %>%
  filter(exType == "ICE" & exFrame == 0)

##simulating intron retention
#get coordinates of introns downstream of first coding exons and internal coding exons
coords.introns <- exons %>%
  filter(totalExNo != exNo) %>%
  filter(geneType == "protein_coding") %>%
  filter(exType %in% c("FCE","ICE")) %>%
  pull(intronCoords.downst) %>%
  unique()

gr.introns <- GRanges(coords.introns)
start(gr.introns) <- start(gr.introns)+1 #+1 to shift from 0-based to 1-based

#retrieve intron sequences
intronSeqs <- as.character(getSeq(genome, gr.introns))
names(intronSeqs) <- coords.introns

#this function inserts a sequence (insertedSeq) at insertPos
# seq.tx.ind is the seq.tx index that we defined earlier
# we use seq.tx for the first argument (seq) of the function
genNewTx.RI <- function(seq, insertedSeq, insertPos, seq.tx.ind){
  res <- paste0(substr(seq[seq.tx.ind], 1, insertPos), insertedSeq, substr(seq[seq.tx.ind], insertPos+1, nchar(seq[seq.tx.ind])))
  return(res)
}
#simulate intron retention
n.rows <- nrow(exons)
interval <- 200000 #number to process at a time; adjust if necessary
n.intervals <-  ceiling(n.rows/interval)
list.temp <- vector("list", length = n.intervals)

for(i in 1:n.intervals){
  list.temp[[i]] <- exons %>%
    slice(((i-1) * (interval) + 1):pmin(n.rows, (i * interval))) %>%
    filter(geneType == "protein_coding") %>%
    filter(totalExNo != exNo) %>%
    filter(exType %in% c("FCE","ICE")) %>%
    filter(!grepl("cds_start_NF|cds_end_NF", tags)) %>% #remove transcripts with no defined CDS start or stop
    mutate(
      seq.RFnew =
        genNewTx.RI(
          seq.tx$seq.RF,
          intronSeqs[match(intronCoords.downst, names(intronSeqs))],
          cRFLen, #insert sequence after exon end
          seq.ind)
      ) %>%
    mutate(
      stop.CDSnew = 
        translate(DNAStringSet(seq.RFnew), if.fuzzy.codon = "X") %>% #translate new RF sequence
        gsub("(?<=\\*).*?$", "", ., perl = TRUE) %>% #remove all sequences after first stop codon
        nchar(.)*3 #multiply AA length by 3 to get nt position of stop codon
  ) %>%
    mutate(
      lastEJC_RFLenNew = ifelse(
        exNo == (totalExNo-1),
        lastEJC_RFLen - exCDSLen, #if it is the last intron, then simply move the lastEJC position up one exon
        lastEJC_RFLen + nchar(intronSeqs[match(intronCoords.downst, names(intronSeqs))]) #otherwise, move the lastEJC position down by the length of inserted intron
      )
    ) %>%
    mutate(
      distLEJC.CDSori = (lastEJC_RFLen - totalCDSLen),
      distLEJC.CDSnew = (lastEJC_RFLenNew - stop.CDSnew)
    ) %>% #distances to last EJC
    select(-seq.RFnew)
  print(i)
}

##NMD status of original and simulated transcripts
exons_RI <- do.call(rbind, list.temp) %>%
  mutate(
    txID_coords = paste0(txID, "_", coords),
    NMD.stat.ori = case_when(
      distLEJC.CDSori >= 50 & (exLen >= 400 | totalCDSLen <= 100) ~ "NMD.lo", #possible chance of NMD mitigation?
      distLEJC.CDSori >= 50 ~ "NMD.hi", #higher chance of NMD
      TRUE ~ "Coding" # likely no NMD
    ),
    NMD.stat.new = case_when(
      distLEJC.CDSnew >= 50 & (exLen >= 400 | stop.CDSnew <= 100) ~ "NMD.lo",
      distLEJC.CDSnew >= 50 ~ "NMD.hi",
      TRUE ~ "Coding"
    )#we treat NMD.lo and NMD.hi as NMD substrates for this analysis, but one could keep both categories seperate if desired
  ) %>%
  mutate(
    NMD.stat.pair = paste0(NMD.stat.ori, ":::", NMD.stat.new) #NMD status of original vs simulated
  )

#(NMD tx becomes coding tx after intron retention)
#introns that reduce NMD upon retention (e.g. shifting last EJC position, altering frame)
introns.rNMD <- exons_RI %>%
  filter(NMD.stat.pair %in% c("NMD.hi:::Coding", "NMD.lo:::Coding"))

#(coding tx becomes NMD tx after intron retention)
#exons that induce NMD upon retention due to downstream frameshifting or PTC inclusion
introns.NMD <- exons_RI %>%
  filter(NMD.stat.pair %in% c("Coding:::NMD.hi", "Coding:::NMD.lo"))

#(coding tx remains coding tx after intron retention)
#introns that alter CDS without frameshifting and NMD
introns.insAA <- exons_RI %>%
  filter(NMD.stat.pair == "Coding:::Coding") %>%
  filter(stop.CDSnew > (cCDSLen + downIntLen) & (downIntLen %% 3) == 0)

#introns that alter CDS with frameshifting but without NMD
introns.insAA_FS <- exons_RI %>%
  filter(NMD.stat.pair == "Coding:::Coding") %>%
  filter(stop.CDSnew > (cCDSLen + downIntLen) & (downIntLen %% 3) != 0)

#introns that alter CDS due to an intronic stop codon but without NMD
introns.intronicStop <- exons_RI %>%
  filter(NMD.stat.pair == "Coding:::Coding") %>%
  filter(stop.CDSnew <= (cCDSLen + downIntLen))

##simulating alternative splice site usage
#create genomicRange object for all exons
GR_exons <- GRanges(
  exons %>%
    mutate(coords = paste0(geneID, ":", gsub("^chr.*?:", "", coords, perl = TRUE))) %>%
    pull(coords)
) #replace chromosome info with geneID
#add other metadata for filtering purposes later
GR_exons$txID_coords <- exons$txID_coords
GR_exons$exNo <- exons$exNo
GR_exons$totalExNo <- exons$totalExNo
GR_exons$exType <- exons$exType

#categorise exon pairs based on matching splice sites and position in transcript
overlap_ex <- as.data.frame(mergeByOverlaps(GR_exons, GR_exons)) %>%
  select(which(grepl("GR_exons", colnames(.)))) %>% 
  rename_with(function(x){gsub("GR_exons\\.", "",x)}) %>%
  mutate(
    #exon position of exon A of comparison
    exPos1 = case_when(
      exNo == 1 ~ "first",
      exNo != totalExNo ~ "internal",
      exNo == totalExNo ~ "last"
    ),
    #exon position of exon B of comparison
    exPos2 = case_when(
      exNo.1 == 1 ~ "first",
      exNo.1 != totalExNo.1 ~ "internal",
      exNo.1 == totalExNo.1 ~ "last"
    ) #these positions refer to positions in transcript, not in terms of protein coding
  ) %>%
  select(
    geneID = seqnames, strand, start1 = start, end1 = end, width1 = width, exPos1, exType1 = exType, txID_coords1 = txID_coords,
    start2 = start.1, end2 = end.1, width2 = width.1, exPos2, exType2 = exType.1, txID_coords2 = txID_coords.1) %>%
  distinct() %>% #remove duplicates
  filter(
    !((start1 == start2) & (end1 == end2)) & (exType1 %in% c("FCE","ICE","LCE") | exType2 %in% c("FCE","ICE","LCE"))
  ) %>% #remove perfect overlaps (i.e. the exact same exon ranges overlapping) and keep pairs with at least one exon being a coding exon
  mutate(
    #these pairs have the same 3'ss and are not the first exons
    match3SS = ifelse(
      (strand == "+" & exPos1 != "first" & exPos2 != "first" & start1 == start2) | 
        (strand == "-" & exPos1 != "first" & exPos2 != "first" & end1 == end2),
      TRUE, FALSE),
    #these pairs have the same 5'ss and are not the last exons
    match5SS = ifelse(
      (strand == "+" & exPos1 != "last" & exPos2 != "last" & end1 == end2) | 
        (strand == "-" & exPos1 != "last" & exPos2 != "last" & start1 == start2),
      TRUE, FALSE),
  )

#create genomicRange object for all introns (all introns this time, not just those after first/internal coding exons)
#we use this to eliminate exon pairs that are not alternative splice sites, but rather produced by intron retention
intronCoords <- rbind(
  exons %>% select(geneID, intronCoords = intronCoords.upst),
  exons %>% select(geneID, intronCoords = intronCoords.downst)
) %>%
  filter(!is.na(intronCoords)) %>%
  distinct() %>%
  mutate(intronCoords = paste0(geneID, ":", gsub("^chr.*?:", "", intronCoords, perl = TRUE))) #swap chromosome info for geneID

GR_introns <- GRanges(intronCoords$intronCoords)

##simulating alternative 3'ss usage
overlap_a3ss <- overlap_ex %>%
  filter(match3SS == FALSE) %>% #pairs without matching 3'ss
  mutate(
    deltaPos3SS = ifelse(
      strand == "+",
      start2 - start1,
      end2 - end1
    )
  ) %>% #calculate distance between alternative splice sites
  filter(exPos1 != "first" & exPos2 != "first") %>% #should not be first exons
  filter(exType1 %in% c("FCE","ICE","LCE")) %>% #we keep the left-hand side as protein coding for simplicity
  mutate(
    dist3SS = ifelse(strand == "+", pmin(start1, start2), pmax(end1, end2)), #i.e. distal; produces longer exon
    prox3SS = ifelse(strand == "+", pmax(start1, start2), pmin(end1, end2)), #i.e. proximal; produces shorter exon
    fixed5SS = ifelse(strand == "+", end1, start1)
    ) #these are the 3' and 5' splice site positions

#make GRange object for the region that is altered by the alt. 3'ss usage (note: not complete exons)
gr.diff3SS <- GRanges(
  paste0(
    overlap_a3ss$geneID, ":",
    pmin(overlap_a3ss$dist3SS, overlap_a3ss$prox3SS), "-",
  pmax(overlap_a3ss$dist3SS, overlap_a3ss$prox3SS), ":",
  overlap_a3ss$strand
  )
)

#overlap these alt. 3'ss extension regions with intronic regions
#only count those where the intron is wholly contained within the 3'ss extension region
ov.introns_diff3SS <- as.data.frame(findOverlaps(GR_introns, gr.diff3SS, type = "within"))

#drop all cases where full introns are detected in the alt. 3'ss extension region
overlap_a3ss <- overlap_a3ss %>% filter(!1:nrow(.) %in% ov.introns_diff3SS$subjectHits)

#preparing for simulating 3'ss
exons_A3 <- exons %>%
  right_join(., overlap_a3ss %>% select(txID_coords = txID_coords1, deltaPos3SS, dist3SS, prox3SS, fixed5SS)) %>%
  filter((exLen - ifelse(strand == "+", deltaPos3SS, deltaPos3SS*-1)) >= 15) %>% #filter: shorter exon form cannot be shorter than 15nt
  filter(!grepl("cds_start_NF|cds_end_NF", tags)) %>% #remove incomplete CDS transcripts
  filter(exType != "FCE") %>% #do not consider first coding exons
  distinct() %>%
  filter(geneType == "protein_coding")

#GRange for the sequences after alt. 3'ss usage
GR.exonsA3 <- GRanges(exons_A3$coords.RF) #first get the full RF coordinates
#then adjust starts and ends based on alt. 3'ss usage
start(GR.exonsA3) <- start(GR.exonsA3) + ifelse(exons_A3$strand == "+", exons_A3$deltaPos3SS, 0)
end(GR.exonsA3) <- end(GR.exonsA3) + ifelse(exons_A3$strand == "+", 0, exons_A3$deltaPos3SS)
#retrieve new sequence
exons_A3 <- exons_A3 %>%
  mutate(
    coords.RFnew = as.character(GR.exonsA3),
    seq.RF_A3 = as.character(getSeq(genome, GR.exonsA3))
    )

##simulating alt. 3'ss usage
#this function drops out a sequence between dropPos.start & dropPos.end (left-hand side exon)
#then inserts a new exon sequence (insertedSeq) based on alt. 3'ss usage (right-hand side exon)
# seq.tx.ind is the seq.tx index that we defined earlier
# we use seq.tx for the first argument (seq) of the function
genNewTx_altSS <- function(seq, dropPos.start, dropPos.end, seq.tx.ind, insertedSeq){
  res <- paste0(substr(seq[seq.tx.ind], 1, dropPos.start), insertedSeq, substr(seq[seq.tx.ind], dropPos.end+1, nchar(seq[seq.tx.ind])))
  return(res)
}

n.rows <- nrow(exons_A3)
interval <- 50000 #adjust as necessary
n.intervals <-  ceiling(n.rows/interval)
list.temp <- vector("list", length = n.intervals)

for(i in 1:n.intervals){
  list.temp[[i]] <- exons_A3 %>%
    slice(((i-1) * (interval) + 1):pmin(n.rows, (i * interval))) %>%
    mutate(seq.RFnew = genNewTx_altSS(seq.tx$seq.RF, cRFLen - exRFLen, cRFLen, seq.ind, seq.RF_A3)) %>%
    mutate(
      stop.CDSnew = 
        translate(DNAStringSet(seq.RFnew)) %>%
        gsub("(?<=\\*).*?$", "", ., perl = TRUE) %>%
        nchar(.)*3) %>%
    mutate(
      RFoffset = nchar(seq.RFnew) - nchar(seq.RF), #how much nucleotides are lost/gained in the new sequence
      lastEJC_RFLenNew = lastEJC_RFLen + RFoffset #adjust last EJC position by RFoffset
    ) %>%
    mutate(
      distLEJC.CDSori = (lastEJC_RFLen - totalCDSLen),
      distLEJC.CDSnew = (lastEJC_RFLenNew - stop.CDSnew)
    ) %>%
    mutate(
      exFrame = (exLen %% 3),
      exFrameNew = (nchar(seq.CDS_A3) %% 3) #check reading frame of new exon
    ) %>%
    select(-seq.RFnew)
  print(i)
}

##NMD status of original and simulated transcripts
exons_A3 <- do.call(rbind, list.temp) %>%
  mutate(
    NMD.stat.ori = case_when(
      distLEJC.CDSori >= 50 & (exLen >= 400 | totalCDSLen <= 100) ~ "NMD.lo",
      distLEJC.CDSori >= 50 ~ "NMD.hi",
      TRUE ~ "Coding"
    ),
    NMD.stat.new = case_when(
      distLEJC.CDSnew >= 50 & (exLen >= 400 | stop.CDSnew <= 100) ~ "NMD.lo",
      distLEJC.CDSnew >= 50 ~ "NMD.hi",
      TRUE ~ "Coding"
    )
  ) %>%
  mutate(
    NMD.stat.pair = paste0(NMD.stat.ori, ":::", NMD.stat.new),
    NMD.stat.distVsProx =
      ifelse(
        strand == "+",
        ifelse(exEnd == dist3SS,
               paste0(NMD.stat.ori, ":::", NMD.stat.new),
               paste0(NMD.stat.new, ":::", NMD.stat.ori)
        ),
        ifelse(exStart == dist3SS,
               paste0(NMD.stat.ori, ":::", NMD.stat.new),
               paste0(NMD.stat.new, ":::", NMD.stat.ori)
        )
      ) #compared to NMD.stat.pair, NMD.stat.distVsProx always has the longer exon on the left-hand side
  )

#longer exon introduces a PTC and triggers NMD, while the shorter exon remains protein coding
A3.PTC_dist <- exons_A3 %>%
  filter(NMD.stat.distVsProx %in% c("NMD.hi:::Coding", "NMD.lo:::Coding")) %>%
  filter(
    (RFoffset > 0 & (stop.CDSnew <= (cCDSLen + RFoffset))) |
      (RFoffset < 0 & (totalCDSLen <= cCDSLen))
  )
#shorter exon introduces a PTC and triggers NMD, while the longer exon remains protein coding
A3.PTC_prox <- exons_A3 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::NMD.hi", "coding:::NMD.lo")) %>%
  filter(
    (RFoffset < 0 & (stop.CDSnew <= (cCDSLen + RFoffset))) |
      (RFoffset > 0 & (totalCDSLen <= cCDSLen))
  )
#longer exon introduces frameshifting and triggers NMD, while the shorter exon remains protein coding
A3.fsNMD_dist <- exons_A3 %>%
  filter(NMD.stat.distVsProx %in% c("NMD.hi:::Coding", "NMD.lo:::Coding")) %>%
  filter(
    (RFoffset > 0 & (stop.CDSnew > (cCDSLen + RFoffset))) |
      (RFoffset < 0 & (totalCDSLen > cCDSLen))
  )
#shorter exon introduces frameshifting and triggers NMD, while the longer exon remains protein coding
A3.fsNMD_prox <- exons_A3 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::NMD.hi", "coding:::NMD.lo")) %>%
  filter(
    (RFoffset < 0 & (stop.CDSnew > (cCDSLen + RFoffset))) |
      (RFoffset > 0 & (totalCDSLen > cCDSLen))
  )
#both exon versions remain frame-preserving and do not trigger NMD
A3.indelCDS <- exons_A3 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::Coding")) %>%
  filter(RFoffset %% 3 == 0)
#both exon versions lead to different reading frames but do not trigger NMD
A3.fsCDS <- exons_A3 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::Coding")) %>%
  filter(RFoffset %% 3 != 0)

##simulating alternative 5'ss usage
overlap_a5ss <- overlap_ex %>%
  filter(match5SS == FALSE) %>% #pairs without matching 5'ss
  mutate(
    deltaPos5SS = ifelse(
      strand == "+",
      end2 - end1,
      start2 - start1
    ) #calculate distance between alternative splice sites
  ) %>%
  filter(exPos1 != "last" & exPos2 != "last") %>% #should not be last exons
  filter(exType1 %in% c("FCE", "ICE", "LCE")) %>% #considering all coding exons
  mutate(
    dist5SS = ifelse(strand == "+", pmax(end1, end2), pmin(start1, start2)),
    prox5SS = ifelse(strand == "+", pmin(end1, end2), pmax(start1, start2)),
    fixed3SS = ifelse(strand == "+", start1, end1)
  ) #these are the positions of the splice sites

#make GRange object for the region that is altered by the alt. 5'ss usage (note: not complete exons)
gr.diff5SS <- GRanges(
  paste0(
    overlap_a5ss$geneID, ":",
    pmin(overlap_a5ss$dist5SS, overlap_a5ss$prox5SS), "-",
    pmax(overlap_a5ss$dist5SS, overlap_a5ss$prox5SS), ":",
    overlap_a5ss$strand
  )
)
#overlap these alt. 5'ss extension regions with intronic regions
#only count those where the intron is wholly contained within the 5'ss extension region
ov.introns_diff5SS <- as.data.frame(findOverlaps(GR_introns, gr.diff5SS, type = "within"))
#drop all cases where full introns are detected in the alt. 5'ss extension region
overlap_a5ss <- overlap_a5ss %>% filter(!1:nrow(.) %in% ov.introns_diff5SS$subjectHits)

#preparing for simulating 3'ss
exons_A5 <- exons %>%
  mutate(downExStart = lead(exStart)) %>%
  right_join(., overlap_a5ss %>% select(txID_coords = txID_coords1, deltaPos5SS, dist5SS, prox5SS, fixed3SS)) %>%
  distinct() %>%
  filter((exLen - ifelse(strand == "+", deltaPos5SS*-1, deltaPos5SS)) >= 15) %>% #filter: shorter exon shouldn't be less than 15nt
  filter(
    exType != "FCE" |
    (exType == "FCE" & (exCDSLen - ifelse(strand == "+", deltaPos5SS*-1, deltaPos5SS)) >= 3) #check if alt 5'ss will delete ATG
  ) %>%
  filter(!grepl("cds_start_NF|cds_end_NF", tags)) %>% #remove incomplete transcripts
  filter(geneType == "protein_coding")

#GRange for the sequences after alt. 5'ss usage
GR.exonsA5 <- GRanges(exons_A5$coords.RF) #first get the full RF coordinates
#then adjust starts and ends based on alt. 5'ss usage
start(GR.exonsA5) <- start(GR.exonsA5) + ifelse(exons_A5$strand == "+", 0, exons_A5$deltaPos5SS)
end(GR.exonsA5) <- end(GR.exonsA5) + ifelse(exons_A5$strand == "+", exons_A5$deltaPos5SS, 0)

#retrieve new sequence
exons_A5 <- exons_A5 %>%
  mutate(
    coords.RFnew = as.character(GR.exonsA5),
    seq.RF_A5 = as.character(getSeq(genome, GR.exonsA5))
    )

##simulating alt. 5'ss usage
n.rows <- nrow(exons_A5)
interval <- 50000
n.intervals <-  ceiling(n.rows/interval)
list.temp <- vector("list", length = n.intervals)
for(i in 1:n.intervals){
  list.temp[[i]] <- exons_A5 %>%
    slice(((i-1) * (interval) + 1):pmin(n.rows, (i * interval))) %>%
    mutate(seq.RFnew = genNewTx_altSS(seq.tx$seq.RF, cRFLen - exRFLen, cRFLen, seq.ind, seq.RF_A5)) %>%
    mutate(
      stop.CDSnew =
        translate(DNAStringSet(seq.RFnew)) %>%
        gsub("(?<=\\*).*?$", "", ., perl = TRUE) %>%
        nchar(.)*3
      ) %>%
    mutate(
      RFoffset = nchar(seq.RF_A5) - nchar(seq.RF), #how much nucleotides are lost/gained in the new sequence
      lastEJC_RFLenNew = lastEJC_RFLen + RFoffset #adjust last EJC position by RFoffset
    ) %>%
    mutate(
      distLEJC.CDSori = (lastEJC_RFLen - totalCDSLen),
      distLEJC.CDSnew = (lastEJC_RFLenNew - stop.CDSnew)
    ) %>%
    mutate(
      exFrame = (exLen %% 3),
      exFrameNew = (nchar(seq.RF_A5) %% 3)
    ) %>%
    select(-seq.RFnew)
  print(i)
}

##NMD status of original and simulated transcripts
exons_A5 <- do.call(rbind, list.temp) %>%
  mutate(
    NMD.stat.ori = case_when(
      distLEJC.CDSori >= 50 & (exLen >= 400 | totalCDSLen <= 100) ~ "NMD.lo",
      distLEJC.CDSori >= 50 ~ "NMD.hi",
      TRUE ~ "Coding"
    ),
    NMD.stat.new = case_when(
      distLEJC.CDSnew >= 50 & (exLen >= 400 | stop.CDSnew <= 100) ~ "NMD.lo",
      distLEJC.CDSnew >= 50 ~ "NMD.hi",
      TRUE ~ "Coding"
    )
  ) %>%
  mutate(
    NMD.stat.pair = paste0(NMD.stat.ori, ":::", NMD.stat.new),
    NMD.stat.distVsProx =
      ifelse(
        strand == "+",
        ifelse(exEnd == dist5SS,
               paste0(NMD.stat.ori, ":::", NMD.stat.new),
               paste0(NMD.stat.new, ":::", NMD.stat.ori)
        ),
        ifelse(exStart == dist5SS,
               paste0(NMD.stat.ori, ":::", NMD.stat.new),
               paste0(NMD.stat.new, ":::", NMD.stat.ori)
        )
      ) #compared to NMD.stat.pair, NMD.stat.distVsProx always has the longer exon on the left-hand side
  )
#longer exon introduces a PTC and triggers NMD, while the shorter exon remains protein coding
A5.PTC_dist <- exons_A5 %>%
  filter(NMD.stat.distVsProx %in% c("NMD.hi:::Coding", "NMD.lo:::Coding")) %>%
  filter(
    (RFoffset > 0 & (stop.CDSnew <= (cCDSLen + RFoffset))) |
    (RFoffset < 0 & (totalCDSLen <= cCDSLen))
    )
#shorter exon introduces a PTC and triggers NMD, while the longer exon remains protein coding
A5.PTC_prox <- exons_A5 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::NMD.hi", "coding:::NMD.lo")) %>%
  filter(
    (RFoffset < 0 & (stop.CDSnew <= (cCDSLen + RFoffset))) |
      (RFoffset > 0 & (totalCDSLen <= cCDSLen))
  )
#longer exon introduces frameshifting and triggers NMD, while the shorter exon remains protein coding
A5.fsNMD_dist <- exons_A5 %>%
  filter(NMD.stat.distVsProx %in% c("NMD.hi:::Coding", "NMD.lo:::Coding")) %>%
  filter(
    (RFoffset > 0 & (stop.CDSnew > (cCDSLen + RFoffset))) |
      (RFoffset < 0 & (totalCDSLen > cCDSLen))
  )
#shorter exon introduces frameshifting and triggers NMD, while the longer exon remains protein coding
A5.fsNMD_prox <- exons_A5 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::NMD.hi", "coding:::NMD.lo")) %>%
  filter(
    (RFoffset < 0 & (stop.CDSnew > (cCDSLen + RFoffset))) |
      (RFoffset > 0 & (totalCDSLen > cCDSLen))
  )
#both exon versions remain frame-preserving and do not trigger NMD
A5.indelCDS <- exons_A5 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::Coding")) %>%
  filter(RFoffset %% 3 == 0)
#both exon versions lead to different reading frames but do not trigger NMD
A5.fsCDS <- exons_A5 %>%
  filter(NMD.stat.distVsProx %in% c("Coding:::Coding")) %>%
  filter(RFoffset %% 3 != 0)

####Collating results of simulated splice events
#Mapping txID_coords back to predicted effects (exon skipping/inclusion & intron retention/splicing)
exons_cons <- exons %>%
  select(geneSym, geneID, txID, exNo, totalExNo, strand, geneType, txType, exType, intronCoords.upst, coords, intronCoords.downst) %>%
  mutate(txID_coords = paste0(txID, "_", coords)) %>%
  left_join(., (exons_CE %>% select(txID_coords, NMDstat.ex = NMD.stat.pair))) %>%
  mutate(
    #effect of exon inclusion/skipping (L3 = effect on specific transcript)
    exTxEff_L3 = case_when(
      !geneType %in% c("protein_coding") ~ "nonCodingGene",
      !exType %in% c("FCE","ICE","LCE") ~ "nonCodingEx", 
      txID_coords %in% c(exons.PTC$txID_coords, exons.sjPTC$txID_coords) ~ "NMD.PTC", #NMD via PTC when included
      txID_coords %in% c(exons.ifsNMD$txID_coords) ~ "NMD.IncFS", #NMD via frameshifting when included
      txID_coords %in% c(exons.sfsNMD$txID_coords) ~ "NMD.SkipFS", #NMD via frameshifting when excluded
      txID_coords %in% c(exons.ICE.altCT$txID_coords) ~ "aCT.ICE", #alt. C-terminus via frameshifting
      txID_coords %in% c(exons.LCE.altCT$txID_coords) ~ "aCT.LCE", #alt. C-terminus via alternative last coding exon
      txID_coords %in% c(exons.ICE.CDSlost$txID_coords) ~ "CDSinframe", #gain/loss of CDS without frameshifting or NMD
      exType == "FCE" ~ "FCE.loss", #start position lost
      TRUE ~ "noAnno" #likely due to incomplete CDSes
    )
  ) %>%
  mutate( #tie-breaker, when necessary, for later (preference goes NMD -> altered coding sequence -> start lost -> non-coding exon)
    exTxEff_L3 = factor(exTxEff_L3, levels = c("nonCodingGene", "NMD.PTC", "NMD.IncFS", "NMD.SkipFS", "aCT.ICE", "aCT.LCE", "CDSinframe", "FCE.loss","nonCodingEx", "noAnno"))
  ) %>%
  left_join(., (exons_RI %>% select(txID_coords, NMDstat.dnInt = NMD.stat.pair))) %>%
  mutate(
    #effect of intron retention/splicing (L2 = effect on specific transcript)
    dnIntTxEff_L2 = case_when(
      !geneType %in% c("protein_coding") ~ "nonCodingGene",
      !exType %in% c("FCE","ICE") ~ "notInCDS",
      txID_coords %in% c(introns.rNMD$txID_coords) ~ "NMD.spl", #NMD when spliced out
      txID_coords %in% c(introns.NMD$txID_coords) ~ "NMD.ret", #NMD when retained
      txID_coords %in% c(introns.insAA$txID_coords) ~ "insCDS.ret", #sequence inserted/removed, no NMD, no frameshifting
      txID_coords %in% c(introns.insAA_FS$txID_coords) ~ "insCDS_FS.ret", #sequence inserted/removed with frameshifting, no NMD
      txID_coords %in% c(introns.intronicStop$txID_coords) ~ "intronicStop.ret", #NMD via PTC when retained, no NMD
      TRUE ~ "noAnno" #remainder (usually due to incomplete CDS transcripts)
    )
  ) %>%
  mutate(#tie-breaker, when necessary, for later (preference goes NMD -> altered coding sequence -> non-coding exon)
    dnIntTxEff_L2 = factor(dnIntTxEff_L2, levels = c("nonCodingGene", "NMD.spl", "NMD.ret", "insCDS.ret", "insCDS_FS.ret", "intronicStop.ret", "noAnno", "notInCDS"))
  )

#effect of exon inclusion/skipping (L2 = effect when considering flanking exons)
exons_cons_L2 <- exons_cons %>%
  mutate(NFtag = ifelse(exTxEff_L3 == "noAnno", TRUE, FALSE)) %>%  #de-prioritise incomplete CDS
  mutate(NCE = ifelse(!exType %in% c("FCE","ICE","LCE"), TRUE, FALSE)) %>% #de-prioritise non-coding exons
  mutate(coords.L2 = paste(geneID, intronCoords.upst, coords, intronCoords.downst, sep = "_")) %>%
  select(coords.L2, NCE, exTxEff_L2 = exTxEff_L3, NFtag) %>%
  group_by_all() %>%
  summarise(n = n(), .groups = "drop") %>% 
  arrange(coords.L2, NCE, NFtag, -n, exTxEff_L2) %>%
  filter(!duplicated(coords.L2)) #keep most common outcome

#effect of exon inclusion/skipping (L1 = effect when considering only the exon itself)
exons_cons_L1 <- exons_cons %>%
  mutate(NFtag = ifelse(exTxEff_L3 == "noAnno", TRUE, FALSE)) %>%
  mutate(NCE = ifelse(!exType %in% c("FCE","ICE","LCE"), TRUE, FALSE)) %>%
  select(geneSym, NCE, coords, exTxEff_L1 = exTxEff_L3, NFtag) %>%
  group_by_all() %>%
  summarise(n = n(), .groups = "drop") %>%
  arrange(geneSym, coords, NCE, NFtag, -n, exTxEff_L1) %>%
  filter(!duplicated(paste(geneSym, coords, sep = "_"))) #keep most common outcome

#effect of intron retention/splicing (L1 = effect when considering only the intron itself)
introns_primaryCons <- exons_cons %>%
  mutate(NFtag = ifelse(dnIntTxEff_L2 == "noAnno", TRUE, FALSE)) %>%
  mutate(NCE = ifelse(!exType %in% c("FCE","ICE","LCE"), TRUE, FALSE)) %>%
  select(geneSym, intronCoords.downst, NCE, dnIntTxEff_L1 = dnIntTxEff_L2, NFtag) %>%
  group_by_all() %>%
  summarise(n = n(), .groups = "drop") %>%
  arrange(geneSym, intronCoords.downst, NCE, NFtag, -n, dnIntTxEff_L1) %>%
  filter(!duplicated(paste0(geneSym, "_", intronCoords.downst))) #keep most common outcome

#insert higher level consequences back
simulTX <- exons_cons %>%
  mutate(coords.L2 = paste(geneID, intronCoords.upst, coords, intronCoords.downst, sep = "_")) %>%
  left_join(., exons_cons_L2 %>% select(coords.L2, exTxEff_L2)) %>%
  left_join(., exons_cons_L1 %>% select(geneSym, coords, exTxEff_L1)) %>%
  left_join(., introns_primaryCons %>% select(geneSym, intronCoords.downst, dnIntTxEff_L1)) %>%
  select(-coords.L2)

#export file
write.table(res.out, "./GENCODEv47_simulatedTx.txt", sep = "\t", row.names = FALSE, quote = FALSE)

#######
#Mapping txID_coords back to predicted effects (alt. 3'ss)
exons_A3cons <- exons_A3 %>%
  select(geneSym, geneID, txID, exNo, totalExNo, chr, strand, geneType, txType, exType, intronCoords.upst, coords, intronCoords.downst, txID_coords, RFoffset, dist3SS, prox3SS, fixed5SS, NMD.stat.pair, NMD.stat.distVsProx) %>%
  mutate(
    #effect of exon inclusion/skipping (L3 = effect on specific transcript)
    A3TxEff_L3 = case_when(
      !geneType %in% c("protein_coding") ~ "nonCodingGene",
      !exType %in% c("FCE","ICE","LCE") ~ "nonCodingEx",
      txID_coords %in% c(A3.PTC_dist$txID_coords) ~ "PTC_dist", #NMD via PTC in longer exon
      txID_coords %in% c(A3.PTC_prox$txID_coords) ~ "PTC_prox", #NMD via PTC in shorter exon
      txID_coords %in% c(A3.fsNMD_dist$txID_coords) ~ "fsNMD_dist", #NMD via frameshifting in longer exon
      txID_coords %in% c(A3.fsNMD_prox$txID_coords) ~ "fsNMD_prox", #NMD via frameshifting in shorter exon
      txID_coords %in% c(A3.indelCDS$txID_coords) ~ "indelCDS", #in-frame changes to CDS
      txID_coords %in% c(A3.fsCDS$txID_coords) ~ "fsCDS", #frameshifted downstream but no NMD
      TRUE ~ "noAnno" #likely due to incomplete CDS
    )
  )

#unique case: what if alt. 3'ss deletes start codon
exons_A3_FCE <- exons %>%
  right_join(., overlap_a3ss %>% select(txID_coords = txID_coords1, deltaPos3SS, dist3SS, prox3SS, fixed5SS)) %>%
  filter((exLen - ifelse(strand == "+", deltaPos3SS, deltaPos3SS*-1)) >= 15) %>%
  filter(!grepl("cds_start_NF|cds_end_NF", tags)) %>%
  #check if first any of the three nucleotides of CDS/RF would be removed by the proximal alt. 3'ss
  filter((exType == "FCE" & ((exLen - exRFLen)+3) < ifelse(strand == "+", deltaPos3SS, deltaPos3SS*-1))) %>% 
  distinct() %>%
  filter(geneType == "protein_coding") %>%
  mutate(
    RFoffset = abs(dist3SS - prox3SS) * (ifelse(exStart == dist3SS | exEnd == dist3SS, -1, 1))
  ) %>%
  mutate(
    NMD.stat.pair = ifelse(sign(RFoffset) == 1, "noStart:::Coding", "Coding:::noStart"),
    NMD.stat.distVsProx = "Coding:::noStart",
    A3TxEff_L3 = "startLost_prox",
    RFoffset = NA
  ) %>%
  select(geneSym, geneID, txID, exNo, totalExNo, chr, strand, geneType, txType, exType, intronCoords.upst, coords, intronCoords.downst, txID_coords, RFoffset, dist3SS, prox3SS, fixed5SS, NMD.stat.pair, NMD.stat.distVsProx, A3TxEff_L3)

#add startLost_prox cases to main alt. 3'ss dataframe
exons_A3cons <- rbind(exons_A3cons, exons_A3_FCE) %>%
  arrange(geneSym, txID, exNo) %>%
  mutate(
    A3TxEff_L3 = factor(A3TxEff_L3, levels = c("nonCodingGene", "PTC_dist", "PTC_prox", "fsNMD_dist", "fsNMD_prox", "indelCDS", "fsCDS", "startLost_prox","nonCodingEx", "noAnno"))
  )

#effect of exon inclusion/skipping (L2 = effect when considering 5'ss status)
exons_A3_cons_L2 <- exons_A3cons %>%
  mutate(coords.L2 = paste(geneID, fixed5SS, dist3SS, prox3SS, sep = "_")) %>%
  select(coords.L2, A3TxEff_L2 = A3TxEff_L3) %>%
  group_by_all() %>%
  summarise(n = n(), .groups = "drop") %>%
  arrange(coords.L2, A3TxEff_L2, -n) %>%
  filter(!duplicated(coords.L2)) %>% #keep most common outcome
  select(-n)

#effect of exon inclusion/skipping (L1 = effect when primarily considering the 3'ss extended region)
exons_A3_cons_L1 <- exons_A3cons %>%
  mutate(coords.L1 = paste(geneID, dist3SS, prox3SS, sep = "_")) %>%
  select(coords.L1, A3TxEff_L1 = A3TxEff_L3) %>%
  group_by_all() %>%
  summarise(n = n(), .groups = "drop") %>%
  arrange(coords.L1, A3TxEff_L1, -n) %>%
  filter(!duplicated(coords.L1)) %>% #keep most common outcome
  select(-n)

#insert higher level consequences
exons_A3cons <- exons_A3cons %>%
  mutate(coords.L2 = paste(geneID, fixed5SS, dist3SS, prox3SS, sep = "_")) %>%
  mutate(coords.L1 = paste(geneID, dist3SS, prox3SS, sep = "_")) %>%
  left_join(., exons_A3_cons_L2) %>%
  left_join(., exons_A3_cons_L1) %>%
  distinct() %>%
  select(-coords.L1, -coords.L2)
#export file
write.table(exons_A3cons, "./GENCODEv47_simulatedTx_A3.txt", sep = "\t", row.names = FALSE, quote = FALSE)

########
#Mapping txID_coords back to predicted effects (alt. 5'ss)
exons_A5cons <- exons_A5 %>%
  select(geneSym, geneID, txID, exNo, totalExNo, chr, strand, geneType, txType, exType, intronCoords.upst, coords, intronCoords.downst, txID_coords, RFoffset, dist5SS, prox5SS, fixed3SS, NMD.stat.pair, NMD.stat.distVsProx) %>%
  mutate(
    #effect of exon inclusion/skipping (L3 = effect on specific transcript)
    A5TxEff_L3 = case_when(
      !geneType %in% c("protein_coding") ~ "nonCodingGene",
      !exType %in% c("FCE","ICE","LCE") ~ "nonCodingEx",
      txID_coords %in% c(A5.PTC_dist$txID_coords) ~ "PTC_dist", #NMD via PTC in longer exon
      txID_coords %in% c(A5.PTC_prox$txID_coords) ~ "PTC_prox", #NMD via PTC in shorter exon
      txID_coords %in% c(A5.fsNMD_dist$txID_coords) ~ "fsNMD_dist", #NMD via frameshifting in longer exon
      txID_coords %in% c(A5.fsNMD_prox$txID_coords) ~ "fsNMD_prox", #NMD via frameshifting in shorter exon
      txID_coords %in% c(A5.indelCDS$txID_coords) ~ "indelCDS", #in-frame changes to CDS
      txID_coords %in% c(A5.fsCDS$txID_coords) ~ "fsCDS", #frameshifted downstream but no NMD
      TRUE ~ "noAnno" #likely due to incomplete CDS
    )
  ) %>%
  mutate(
    A5TxEff_L3 = factor(A5TxEff_L3, levels = c("nonCodingGene", "PTC_dist", "PTC_prox", "fsNMD_dist", "fsNMD_prox", "indelCDS", "fsCDS","nonCodingEx", "noAnno"))
  )

#effect of exon inclusion/skipping (L2 = effect when primarily considering 3'ss status)
exons_A5_cons_L2 <- exons_A5cons %>%
  mutate(coords.L2 = paste(geneID, fixed3SS, dist5SS, prox5SS, sep = "_")) %>%
  select(coords.L2, A5TxEff_L2 = A5TxEff_L3) %>%
  group_by_all() %>%
  summarise(n = n(), .groups = "drop") %>%
  arrange(coords.L2, A5TxEff_L2, -n) %>%
  filter(!duplicated(coords.L2)) %>% #keep most common outcome
  select(-n)
#effect of exon inclusion/skipping (L1 = effect when primarily considering the 5'ss extended region)
exons_A5_cons_L1 <- exons_A5cons %>%
  mutate(coords.L1 = paste(geneID, dist5SS, prox5SS, sep = "_")) %>%
  select(coords.L1, A5TxEff_L1 = A5TxEff_L3) %>%
  group_by_all() %>%
  summarise(n = n(), .groups = "drop") %>%
  arrange(coords.L1, A5TxEff_L1, -n) %>%
  filter(!duplicated(coords.L1)) %>% #keep most common outcome
  select(-n)

#insert higher level consequences
exons_A5cons <- exons_A5cons %>%
  mutate(coords.L2 = paste(geneID, fixed3SS, dist5SS, prox5SS, sep = "_")) %>%
  mutate(coords.L1 = paste(geneID, dist5SS, prox5SS, sep = "_")) %>%
  left_join(., exons_A5_cons_L2) %>%
  left_join(., exons_A5_cons_L1) %>%
  distinct() %>%
  select(-coords.L1, -coords.L2)
#export file
write.table(exons_A5cons, "./GENCODEv47_simulatedTx_A5.txt", sep = "\t", row.names = FALSE, quote = FALSE)

####these files can be now be used to annotate splicing events based on coordinates