####This script maps UniProt protein features (separated into exon blocks) onto exons, taking into account various AS patterns
library(GenomicRanges)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)

setwd("C:/dataprocessing/database")

####Read required files
#Effects on AS on transcript function (protein-coding, NMD, etc...)
#generated by A_ASeffectsOnTanscripts_allExons.R
exons_simulTx <- read.table("./gencode/GENCODEv47_simulatedTx.txt", sep = "\t", header = TRUE)
#UniProt protein features mapped onto exons
#generated by B_mappingUniprotFeatures.R
exons_protFeats <- read.table("./uniprot/GENCODEv47_exonUniprotFeats.txt", sep = "\t", header = TRUE, quote = "$")

exons_comb <- exons_simulTx %>%
  left_join(., exons_protFeats) %>%
  #count number of protein feature types encoded by each exon
  mutate(n.featTypes_ex = rowSums(!is.na(.[,which(grepl("name_", colnames(.)))]))) %>%
  #change AS effect on transcript function if it is not NMD or frameshift, and overlaps a protein feature
  mutate(exTxEff_L1 = ifelse(n.featTypes_ex != 0 & exTxEff_L1 %in% c("noAnno", "CDSinframe"), "altProtFeat", exTxEff_L1)) %>%
  mutate(exTxEff_L2 = ifelse(n.featTypes_ex != 0 & exTxEff_L2 %in% c("noAnno", "CDSinframe"), "altProtFeat", exTxEff_L2)) %>%
  mutate(exTxEff_L3 = ifelse(n.featTypes_ex != 0 & exTxEff_L3 %in% c("noAnno", "CDSinframe"), "altProtFeat", exTxEff_L3)) %>%
  group_by(txID) %>%
  #count number of features encoded by downstream exons (for the case of frameshifting, truncating, or alt.Cter AS events)
  mutate(n_featTypes_downstr = lead(rev(cumsum(rev(n.featTypes_ex))))) %>%
  ungroup()

####Retrieve protein features that are gained/lost when an exon induces frameshifting upon inclusion/exclusion
txSE_CDSlost <- exons_comb %>%
  filter(exTxEff_L1 %in% c("aCT.ICE", "aCT.LCE") & n_featTypes_downstr != 0)

SE.CDSeff <- lapply(
  1:nrow(txSE_CDSlost),
  function(x){
    subsequentExons <- exons_comb %>%
      filter(txID == txSE_CDSlost$txID[x] & (exNo >= (txSE_CDSlost$exNo[x]+1))) %>%
      select(which(grepl("name_|blockPct_", colnames(.))))
    
    if(any(rowSums(!is.na(subsequentExons[,which(grepl("name_", colnames(subsequentExons)))])) != 0)){
      res <- subsequentExons %>%
        summarise_all(.funs = function(x){paste(na.omit(x), collapse = "; ")}) %>%
        mutate(across(everything(), .fns = function(y){ifelse(y == "", NA, y)}))
      res <- cbind(data.frame(txID = txSE_CDSlost$txID[x], exNo = txSE_CDSlost$exNo[x]), res)
    } else {
      res <- NA
    }
    return(res)
  }
) %>% do.call(rbind, .) %>%
  filter(!is.na(txID))

####Retrieve protein features that are gained/lost when an exon intron frameshifting upon retention
txRI_CDSlost <- exons_comb %>%
  filter(dnIntTxEff_L1 %in% c("insCDS_FS.ret", "intronicStop.ret") & n_featTypes_downstr != 0)

RI.CDSeff <- lapply(
  1:nrow(txRI_CDSlost),
  function(x){
    subsequentExons <- exons_comb %>%
      ungroup() %>%
      filter(txID == txRI_CDSlost$txID[x] & (exNo >= (txRI_CDSlost$exNo[x]+1))) %>%
      select(which(grepl("name_|blockPct_", colnames(.))))
    
    if(any(rowSums(!is.na(subsequentExons[,which(grepl("name_", colnames(subsequentExons)))])) != 0)){
      res <- subsequentExons %>%
        summarise_all(.funs = function(x){paste(na.omit(x), collapse = "; ")}) %>%
        mutate(across(everything(), .fns = function(y){ifelse(y == "", NA, y)}))
      res <- cbind(data.frame(txID = txRI_CDSlost$txID[x], exNo = txRI_CDSlost$exNo[x]), res)
    } else {
      res <- NA
    }
    return(res)
  }
) %>% do.call(rbind, .) %>%
  filter(!is.na(txID))

####export files for use in annotated rMATS
#this file has updated AS functional effects on transcripts (includes protein features essentially)
write.table(exons_comb, "./gencode/GENCODEv47_simulatedTxCons.txt", sep = "\t", row.names = FALSE, quote = FALSE)
#this file has the features disrupted upon frameshifting caused by cassette exons
write.table(SE.CDSeff, "./gencode/GENCODEv47_SE_altCter.txt", sep = "\t", row.names = FALSE, quote = FALSE)
#this file has the features disrupted upon frameshifting caused by intron retention
rite.table(RI.CDSeff, "./gencode/GENCODEv47_RI_nonNMD_FS_PTC.txt", sep = "\t", row.names = FALSE, quote = FALSE)
